// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type CustomGroupsMembersAddRequest struct {
	// groupId to filter on
	ID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Custom Group Members properties
	CustomGroupMembersBody shared.CustomGroupMembersBody `request:"mediaType=application/json"`
}

func (c *CustomGroupsMembersAddRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomGroupsMembersAddRequest) GetCustomGroupMembersBody() shared.CustomGroupMembersBody {
	if c == nil {
		return shared.CustomGroupMembersBody{}
	}
	return c.CustomGroupMembersBody
}

type CustomGroupsMembersAddResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	EmptyResponse *shared.EmptyResponse
	// Bad Request
	Error *shared.Error
}

func (c *CustomGroupsMembersAddResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CustomGroupsMembersAddResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CustomGroupsMembersAddResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CustomGroupsMembersAddResponse) GetEmptyResponse() *shared.EmptyResponse {
	if c == nil {
		return nil
	}
	return c.EmptyResponse
}

func (c *CustomGroupsMembersAddResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
