// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type CustomGroupGetRequest struct {
	// groupId to filter on
	ID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *CustomGroupGetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CustomGroupGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CustomGroupResponse *shared.CustomGroupResponse
	// Bad Request
	Error *shared.Error
}

func (o *CustomGroupGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CustomGroupGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CustomGroupGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CustomGroupGetResponse) GetCustomGroupResponse() *shared.CustomGroupResponse {
	if o == nil {
		return nil
	}
	return o.CustomGroupResponse
}

func (o *CustomGroupGetResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
