// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type CustomGroupsDeleteRequest struct {
	// groupId to filter on
	ID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *CustomGroupsDeleteRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CustomGroupsDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	Error *shared.Error
}

func (o *CustomGroupsDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CustomGroupsDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CustomGroupsDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CustomGroupsDeleteResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
