// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type CustomGroupsCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CustomGroupResponse *shared.CustomGroupResponse
	// Bad Request
	Error *shared.Error
}

func (c *CustomGroupsCreateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CustomGroupsCreateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CustomGroupsCreateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CustomGroupsCreateResponse) GetCustomGroupResponse() *shared.CustomGroupResponse {
	if c == nil {
		return nil
	}
	return c.CustomGroupResponse
}

func (c *CustomGroupsCreateResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
