// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type InboundRuleUpdateRequest struct {
	// The id of the rule
	ID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// Rule properties
	RuleBody shared.RuleBody `request:"mediaType=application/json"`
}

func (i *InboundRuleUpdateRequest) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InboundRuleUpdateRequest) GetRuleBody() shared.RuleBody {
	if i == nil {
		return shared.RuleBody{}
	}
	return i.RuleBody
}

type InboundRuleUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RuleResponse *shared.RuleResponse
	// Bad Request
	Error *shared.Error
}

func (i *InboundRuleUpdateResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *InboundRuleUpdateResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *InboundRuleUpdateResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}

func (i *InboundRuleUpdateResponse) GetRuleResponse() *shared.RuleResponse {
	if i == nil {
		return nil
	}
	return i.RuleResponse
}

func (i *InboundRuleUpdateResponse) GetError() *shared.Error {
	if i == nil {
		return nil
	}
	return i.Error
}
