// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type InboundRulesCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RuleResponse *shared.RuleResponse
	// Bad Request
	Error *shared.Error
}

func (i *InboundRulesCreateResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *InboundRulesCreateResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *InboundRulesCreateResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}

func (i *InboundRulesCreateResponse) GetRuleResponse() *shared.RuleResponse {
	if i == nil {
		return nil
	}
	return i.RuleResponse
}

func (i *InboundRulesCreateResponse) GetError() *shared.Error {
	if i == nil {
		return nil
	}
	return i.Error
}
