// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type InboundRuleUpdateRequest struct {
	// The id of the rule
	ID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// Rule properties
	RuleBody shared.RuleBody `request:"mediaType=application/json"`
}

func (o *InboundRuleUpdateRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *InboundRuleUpdateRequest) GetRuleBody() shared.RuleBody {
	if o == nil {
		return shared.RuleBody{}
	}
	return o.RuleBody
}

type InboundRuleUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RuleResponse *shared.RuleResponse
	// Bad Request
	Error *shared.Error
}

func (o *InboundRuleUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *InboundRuleUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *InboundRuleUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *InboundRuleUpdateResponse) GetRuleResponse() *shared.RuleResponse {
	if o == nil {
		return nil
	}
	return o.RuleResponse
}

func (o *InboundRuleUpdateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
