// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAInboundPoliciesDeleteRequest struct {
	// The id of the MFA policy
	ID string `pathParam:"style=simple,explode=false,name=reactivePolicyId"`
}

func (m *MFAInboundPoliciesDeleteRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

type MFAInboundPoliciesDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	Error *shared.Error
}

func (m *MFAInboundPoliciesDeleteResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MFAInboundPoliciesDeleteResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MFAInboundPoliciesDeleteResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}

func (m *MFAInboundPoliciesDeleteResponse) GetError() *shared.Error {
	if m == nil {
		return nil
	}
	return m.Error
}
