// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAInboundPoliciesCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReactivePolicyItem *shared.ReactivePolicyItem
	// Bad Request
	Error *shared.Error
}

func (m *MFAInboundPoliciesCreateResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MFAInboundPoliciesCreateResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MFAInboundPoliciesCreateResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}

func (m *MFAInboundPoliciesCreateResponse) GetReactivePolicyItem() *shared.ReactivePolicyItem {
	if m == nil {
		return nil
	}
	return m.ReactivePolicyItem
}

func (m *MFAInboundPoliciesCreateResponse) GetError() *shared.Error {
	if m == nil {
		return nil
	}
	return m.Error
}
