// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAInboundPoliciesUpdateRequest struct {
	// The id of the MFA policy
	ID string `pathParam:"style=simple,explode=false,name=reactivePolicyId"`
	// Rule properties
	ReactivePolicyInboundBody shared.ReactivePolicyInboundBody `request:"mediaType=application/json"`
}

func (o *MFAInboundPoliciesUpdateRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MFAInboundPoliciesUpdateRequest) GetReactivePolicyInboundBody() shared.ReactivePolicyInboundBody {
	if o == nil {
		return shared.ReactivePolicyInboundBody{}
	}
	return o.ReactivePolicyInboundBody
}

type MFAInboundPoliciesUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReactivePolicyItem *shared.ReactivePolicyItem
	// Bad Request
	Error *shared.Error
}

func (o *MFAInboundPoliciesUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MFAInboundPoliciesUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MFAInboundPoliciesUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MFAInboundPoliciesUpdateResponse) GetReactivePolicyItem() *shared.ReactivePolicyItem {
	if o == nil {
		return nil
	}
	return o.ReactivePolicyItem
}

func (o *MFAInboundPoliciesUpdateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
