// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAInboundPoliciesGetRequest struct {
	// The id of the MFA policy
	ID string `pathParam:"style=simple,explode=false,name=reactivePolicyId"`
}

func (m *MFAInboundPoliciesGetRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

type MFAInboundPoliciesGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReactivePolicyResponse *shared.ReactivePolicyResponse
	// Bad Request
	Error *shared.Error
}

func (m *MFAInboundPoliciesGetResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MFAInboundPoliciesGetResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MFAInboundPoliciesGetResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}

func (m *MFAInboundPoliciesGetResponse) GetReactivePolicyResponse() *shared.ReactivePolicyResponse {
	if m == nil {
		return nil
	}
	return m.ReactivePolicyResponse
}

func (m *MFAInboundPoliciesGetResponse) GetError() *shared.Error {
	if m == nil {
		return nil
	}
	return m.Error
}
