// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAOutboundPoliciesUpdateRequest struct {
	// The id of the MFA policy
	ID string `pathParam:"style=simple,explode=false,name=reactivePolicyId"`
	// Reactive Policy properties
	ReactivePolicyOutboundBody shared.ReactivePolicyOutboundBody `request:"mediaType=application/json"`
}

func (m *MFAOutboundPoliciesUpdateRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MFAOutboundPoliciesUpdateRequest) GetReactivePolicyOutboundBody() shared.ReactivePolicyOutboundBody {
	if m == nil {
		return shared.ReactivePolicyOutboundBody{}
	}
	return m.ReactivePolicyOutboundBody
}

type MFAOutboundPoliciesUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReactivePolicyItem *shared.ReactivePolicyItem
	// Bad Request
	Error *shared.Error
}

func (m *MFAOutboundPoliciesUpdateResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MFAOutboundPoliciesUpdateResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MFAOutboundPoliciesUpdateResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}

func (m *MFAOutboundPoliciesUpdateResponse) GetReactivePolicyItem() *shared.ReactivePolicyItem {
	if m == nil {
		return nil
	}
	return m.ReactivePolicyItem
}

func (m *MFAOutboundPoliciesUpdateResponse) GetError() *shared.Error {
	if m == nil {
		return nil
	}
	return m.Error
}
