// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type MFAOutboundPoliciesGetRequest struct {
	// The id of the MFA policy
	ID string `pathParam:"style=simple,explode=false,name=reactivePolicyId"`
}

func (o *MFAOutboundPoliciesGetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type MFAOutboundPoliciesGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReactivePolicyResponse *shared.ReactivePolicyResponse
	// Bad Request
	Error *shared.Error
}

func (o *MFAOutboundPoliciesGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MFAOutboundPoliciesGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MFAOutboundPoliciesGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MFAOutboundPoliciesGetResponse) GetReactivePolicyResponse() *shared.ReactivePolicyResponse {
	if o == nil {
		return nil
	}
	return o.ReactivePolicyResponse
}

func (o *MFAOutboundPoliciesGetResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
