// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type OutboundRulesCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RuleResponse *shared.RuleResponse
	// Bad Request
	Error *shared.Error
}

func (o *OutboundRulesCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OutboundRulesCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OutboundRulesCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OutboundRulesCreateResponse) GetRuleResponse() *shared.RuleResponse {
	if o == nil {
		return nil
	}
	return o.RuleResponse
}

func (o *OutboundRulesCreateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
