// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type RPCRuleDeleteRequest struct {
	// The id of the rule
	ID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (r *RPCRuleDeleteRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RPCRuleDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	Error *shared.Error
}

func (r *RPCRuleDeleteResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RPCRuleDeleteResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RPCRuleDeleteResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RPCRuleDeleteResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
