// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

type RPCRuleGetRequest struct {
	// The id of the rule
	ID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (r *RPCRuleGetRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RPCRuleGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RPCRuleResponse *shared.RPCRuleResponse
	// Bad Request
	Error *shared.Error
}

func (r *RPCRuleGetResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RPCRuleGetResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RPCRuleGetResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RPCRuleGetResponse) GetRPCRuleResponse() *shared.RPCRuleResponse {
	if r == nil {
		return nil
	}
	return r.RPCRuleResponse
}

func (r *RPCRuleGetResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
