// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AssetStatus - Possible asset status:
//   - '1' - Not monitored
//   - '2' - Segment server
//   - '4' - Can't be monitored (unsupported OS)
//   - '5' - Can't be monitored (unmonitorable)
//   - '6' - Can't be monitored (unmonitorable)
//   - '7' - Cloud connector
//   - '8' - Not monitored (ansible unreachable)
//   - '9' - Not monitored (cloud connector uninstalled)
//   - '10' - Not monitored (cloud connector required)
//   - '12' - Can't be monitored (inactive entity)
//   - '13' - Stalked Externally
//   - '14' - Lightweight Agent
type AssetStatus int64

const (
	AssetStatusOne      AssetStatus = 1
	AssetStatusTwo      AssetStatus = 2
	AssetStatusFour     AssetStatus = 4
	AssetStatusFive     AssetStatus = 5
	AssetStatusSix      AssetStatus = 6
	AssetStatusSeven    AssetStatus = 7
	AssetStatusEight    AssetStatus = 8
	AssetStatusNine     AssetStatus = 9
	AssetStatusTen      AssetStatus = 10
	AssetStatusTwelve   AssetStatus = 12
	AssetStatusThirteen AssetStatus = 13
	AssetStatusFourteen AssetStatus = 14
)

func (e AssetStatus) ToPointer() *AssetStatus {
	return &e
}
func (e *AssetStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 4:
		fallthrough
	case 5:
		fallthrough
	case 6:
		fallthrough
	case 7:
		fallthrough
	case 8:
		fallthrough
	case 9:
		fallthrough
	case 10:
		fallthrough
	case 12:
		fallthrough
	case 13:
		fallthrough
	case 14:
		*e = AssetStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssetStatus: %v", v)
	}
}
