// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AssetType - Possible asset status:
//   - '0' - Unknown
//   - '1' - Client
//   - '2' - Server
//   - '3' - Virtual cluster
//   - '4' - IP camera
//   - '5' - Smart TV
//   - '6' - Factory controller
//   - '7' - Medical device
//   - '8' - Printer
//   - '9' - Scanner
//   - '10' - Smart card reader
//   - '11' - Router
//   - '12' - Hypervisor
//   - '13' - PLC
//   - '14' - HMI
//   - '15' - Switch
//   - '16' - Terminal station
//   - '17' - RTU
//   - '18' - Wireless access point
//   - '19' - Historian
//   - '20' - Game console
//   - '21' - Fire alarm
//   - '22' - UPS
//   - '23' - Storage appliance
//   - '24' - Virtualization appliance
//   - '25' - Firewall appliance
//   - '26' - Security scanner
//   - '27' - Security controller
//   - '28 ' - Door lock
//   - '29' - Biometric entry system
//   - '30' - HVAC
//   - '31' - Room scheduler
//   - '32' - Load Balancer Appliance
//   - '33' - WAN Concentrator
//   - '34' - IPAM Appliance
//   - '35' - TEMPERATURE SENSOR GATEWAY
//   - '36' - POWER METER
//   - '37' - CONVEYOR SYSTEM
//   - '38' - BUILDING AUTOMATION DEVICE
//   - '39' - VISION CONTROLLER
//   - '40' - MANUFACTURING EXECUTION SYSTEM
//   - '41' - BACNET BROADCAST MANAGEMENT DEVICE BBMD
//   - '42' - BACNET ROUTER AND BBMD
//   - '43' - CLOCK
//   - '44' - RFID
//   - '45' - SCALE
//   - '46' - MOBILE PRINTER
//   - '47' - IED
//   - '48' - CNC MILL
//   - '49' - ROOM MONITOR
//   - '50' - SMART SPEAKER
//   - '51' - VENDING MACHINE
//   - '52' - AUTONOMOUS VEHICLE
//   - '53' - FLEET MANAGEMENT SYSTEM
//   - '54' - BACNET ROUTER
//   - '55' - MOTOR CONTROLLER
//   - '56' - OT GATEWAY
//   - '57' - CONTROLLER
//   - '58' - BUILDING MANAGEMENT SYSTEM
//   - '59' - VOIP PHONE
//   - '60' - VISION SENSOR
//   - '61' - REMOTE IO
//   - '62' - VOIP SERVER
//   - '63' - FLOW METER
//   - '64' - BUILDING AUTOMATION CONTROLLER
//   - '65' - SECURITY CAMERA
//   - '66' - DIGITAL SIGN
//   - '67' - REMOTE ACCESS GATEWAY
//   - '68' - TEMPERATURE SENSOR
//   - '69' - RTLS
//   - '70' - SERIAL TO ETHERNET
//   - '71' - INTERCOM
//   - '72' - ENGINEERING STATION
//   - '73' - DATA LOGGER GATEWAY
//   - '74' - ROBOT
//   - '75' - TABLET
//   - '76' - SCADA SERVER
//   - '77' - INDUSTRIAL PRINTER
//   - '78' - VISION CAMERA
//   - '79' - TIME CLOCK
//   - '80' - VIDEO CONFERENCE
//   - '81' - ELECTRICAL DRIVE
//   - '82' - ACCESS CONTROL
//   - '83' - PRINTER 3D
//   - '84' - ACCESS CONTROL GATEWAY
//   - '85' - ATM
//   - '86' - AUDIO DECODER
//   - '87' - AV SYSTEM
//   - '88' - BACNET ROUTER BBMD
//   - '89' - BADGE READER
//   - '90' - BARCODE SCANNER
//   - '91' - BUILDING AUTOMATION CONTROLLER GATEWAY
//   - '92' - BUILDING MANAGEMENT SENSOR
//   - '93' - BUILDING MANAGEMENT SENSOR GATEWAY
//   - '94' - BUILDING MANAGEMENT SYSTEM GATEWAY
//   - '95' - CAR
//   - '96' - CIRCUIT MONITOR
//   - '97' - CLINICAL MOBILE DEVICE
//   - '98' - CLINICAL MOBILE DEVICE GATEWAY
//   - '99' - CLOCK GATEWAY
//   - '100' - CNC SYSTEM
//   - '101' - CONFERENCE ROOM
//   - '102' - DATA LOGGER
//   - '103' - DIGITAL SIGN WORKSTATION
//   - '104' - DISK PUBLISHER
//   - '105' - DISPATCHER
//   - '106' - EMBEDDED PC
//   - '107' - ENCODER
//   - '108' - EV CHARGING
//   - '109' - FITNESS DEVICE
//   - '110' - GENERIC MOBILE DEVICE
//   - '111' - GPS NAVIGATOR
//   - '112' - INDUSTRIAL BARCODE SCANNER
//   - '113' - INDUSTRIAL METAL DETECTOR
//   - '114' - INDUSTRIAL NETWORK EQUIPMENT
//   - '115' - INDUSTRIAL THIN CLIENT
//   - '116' - INDUSTRIAL THIN CLIENT GATEWAY
//   - '117' - INDUSTRIAL WIRELESS
//   - '118' - INDUSTRIAL WORKSTATION
//   - '119' - INSPECTION SYSTEM
//   - '120' - INTERACTIVE VOICE RESPONSE
//   - '121' - INTERCOM GATEWAY
//   - '122' - IOT CONTROLLER
//   - '123' - LOCK BOX
//   - '124' - MACHINERY HEALTH ANALYZER
//   - '125' - MAILING SYSTEM
//   - '126' - MEDIA GATEWAY
//   - '127' - MEDIA PLAYER
//   - '128' - MEDIA STREAMER
//   - '129' - MICROSCOPE
//   - '130' - MOBILE COMPUTER
//   - '131' - MOTOR STARTER
//   - '132' - MUSICAL INSTRUMENT
//   - '133' - OPC SERVER
//   - '134' - ORDER FULFILLMENT SYSTEM
//   - '135' - OT DEVICE
//   - '136' - OT SERVER
//   - '137' - PA SYSTEM
//   - '138' - PAYMENT KIOSK
//   - '139' - PHYSICAL SECURITY PLATFORM
//   - '140' - POINT OF SALE
//   - '141' - POINT OF SALE GATEWAY
//   - '142' - POWER DISTRIBUTION UNIT
//   - '143' - POWER DISTRIBUTION UNIT GATEWAY
//   - '144' - POWER SUPPLY
//   - '145' - PRINT SERVER
//   - '146' - PROJECTOR
//   - '147' - RADIO
//   - '148' - RADIO REPEATER
//   - '149' - RECORDING SERVER
//   - '150' - REPORTING SERVER
//   - '151' - ROOM AUTOMATION STATION
//   - '152' - ROOM DISPLAY
//   - '153' - RTLS GATEWAY
//   - '154' - SAFETY SYSTEM
//   - '155' - SCADA CLIENT
//   - '156' - SCREEN SHARE
//   - '157' - SECURITY XRAY SCANNER
//   - '158' - SENSOR
//   - '159' - SERIAL TO ETHERNET GATEWAY
//   - '160' - SERVICE TROLLEY
//   - '161' - SMART BOARD
//   - '162' - SMART HOME
//   - '163' - SMART LIGHT
//   - '164' - SMART LIGHT GATEWAY
//   - '165' - SMART LOCK CONTROLLER
//   - '166' - SMARTPHONE
//   - '167' - SMARTWATCH
//   - '168' - SOLAR ENERGY
//   - '169' - TIME CLOCK GATEWAY
//   - '170' - VIDEO CONFERENCE GATEWAY
//   - '171' - VIDEO DECODER
//   - '172' - VIDEO ENCODER
//   - '173' - VIDEO SURVEILLANCE DEVICE
//   - '174' - VOIP ADAPTER
//   - '175' - VOIP PHONE GATEWAY
//   - '176' - WATER SYSTEM
//   - '177' - WIRELESS PHONE
//   - '178' - WIRELESS PHONE GATEWAY
//   - '1001' - OTHER OT
type AssetType int

const (
	AssetTypeZero                      AssetType = 0
	AssetTypeOne                       AssetType = 1
	AssetTypeTwo                       AssetType = 2
	AssetTypeThree                     AssetType = 3
	AssetTypeFour                      AssetType = 4
	AssetTypeFive                      AssetType = 5
	AssetTypeSix                       AssetType = 6
	AssetTypeSeven                     AssetType = 7
	AssetTypeEight                     AssetType = 8
	AssetTypeNine                      AssetType = 9
	AssetTypeTen                       AssetType = 10
	AssetTypeEleven                    AssetType = 11
	AssetTypeTwelve                    AssetType = 12
	AssetTypeThirteen                  AssetType = 13
	AssetTypeFourteen                  AssetType = 14
	AssetTypeFifteen                   AssetType = 15
	AssetTypeSixteen                   AssetType = 16
	AssetTypeSeventeen                 AssetType = 17
	AssetTypeEighteen                  AssetType = 18
	AssetTypeNineteen                  AssetType = 19
	AssetTypeTwenty                    AssetType = 20
	AssetTypeTwentyOne                 AssetType = 21
	AssetTypeTwentyTwo                 AssetType = 22
	AssetTypeTwentyThree               AssetType = 23
	AssetTypeTwentyFour                AssetType = 24
	AssetTypeTwentyFive                AssetType = 25
	AssetTypeTwentySix                 AssetType = 26
	AssetTypeTwentySeven               AssetType = 27
	AssetTypeTwentyNine                AssetType = 29
	AssetTypeThirty                    AssetType = 30
	AssetTypeThirtyOne                 AssetType = 31
	AssetTypeThirtyTwo                 AssetType = 32
	AssetTypeThirtyThree               AssetType = 33
	AssetTypeThirtyFour                AssetType = 34
	AssetTypeThirtyFive                AssetType = 35
	AssetTypeThirtySix                 AssetType = 36
	AssetTypeThirtySeven               AssetType = 37
	AssetTypeThirtyEight               AssetType = 38
	AssetTypeThirtyNine                AssetType = 39
	AssetTypeForty                     AssetType = 40
	AssetTypeFortyOne                  AssetType = 41
	AssetTypeFortyTwo                  AssetType = 42
	AssetTypeFortyThree                AssetType = 43
	AssetTypeFortyFour                 AssetType = 44
	AssetTypeFortyFive                 AssetType = 45
	AssetTypeFortySix                  AssetType = 46
	AssetTypeFortySeven                AssetType = 47
	AssetTypeFortyEight                AssetType = 48
	AssetTypeFortyNine                 AssetType = 49
	AssetTypeFifty                     AssetType = 50
	AssetTypeFiftyOne                  AssetType = 51
	AssetTypeFiftyTwo                  AssetType = 52
	AssetTypeFiftyThree                AssetType = 53
	AssetTypeFiftyFour                 AssetType = 54
	AssetTypeFiftyFive                 AssetType = 55
	AssetTypeFiftySix                  AssetType = 56
	AssetTypeFiftySeven                AssetType = 57
	AssetTypeFiftyEight                AssetType = 58
	AssetTypeFiftyNine                 AssetType = 59
	AssetTypeSixty                     AssetType = 60
	AssetTypeSixtyOne                  AssetType = 61
	AssetTypeSixtyTwo                  AssetType = 62
	AssetTypeSixtyThree                AssetType = 63
	AssetTypeSixtyFour                 AssetType = 64
	AssetTypeSixtyFive                 AssetType = 65
	AssetTypeSixtySix                  AssetType = 66
	AssetTypeSixtySeven                AssetType = 67
	AssetTypeSixtyEight                AssetType = 68
	AssetTypeSixtyNine                 AssetType = 69
	AssetTypeSeventy                   AssetType = 70
	AssetTypeSeventyOne                AssetType = 71
	AssetTypeSeventyTwo                AssetType = 72
	AssetTypeSeventyThree              AssetType = 73
	AssetTypeSeventyFour               AssetType = 74
	AssetTypeSeventyFive               AssetType = 75
	AssetTypeSeventySix                AssetType = 76
	AssetTypeSeventySeven              AssetType = 77
	AssetTypeSeventyEight              AssetType = 78
	AssetTypeSeventyNine               AssetType = 79
	AssetTypeEighty                    AssetType = 80
	AssetTypeEightyOne                 AssetType = 81
	AssetTypeEightyTwo                 AssetType = 82
	AssetTypeEightyThree               AssetType = 83
	AssetTypeEightyFour                AssetType = 84
	AssetTypeEightyFive                AssetType = 85
	AssetTypeEightySix                 AssetType = 86
	AssetTypeEightySeven               AssetType = 87
	AssetTypeEightyEight               AssetType = 88
	AssetTypeEightyNine                AssetType = 89
	AssetTypeNinety                    AssetType = 90
	AssetTypeNinetyOne                 AssetType = 91
	AssetTypeNinetyTwo                 AssetType = 92
	AssetTypeNinetyThree               AssetType = 93
	AssetTypeNinetyFour                AssetType = 94
	AssetTypeNinetyFive                AssetType = 95
	AssetTypeNinetySix                 AssetType = 96
	AssetTypeNinetySeven               AssetType = 97
	AssetTypeNinetyEight               AssetType = 98
	AssetTypeNinetyNine                AssetType = 99
	AssetTypeOneHundred                AssetType = 100
	AssetTypeOneHundredAndOne          AssetType = 101
	AssetTypeOneHundredAndTwo          AssetType = 102
	AssetTypeOneHundredAndThree        AssetType = 103
	AssetTypeOneHundredAndFour         AssetType = 104
	AssetTypeOneHundredAndFive         AssetType = 105
	AssetTypeOneHundredAndSix          AssetType = 106
	AssetTypeOneHundredAndSeven        AssetType = 107
	AssetTypeOneHundredAndEight        AssetType = 108
	AssetTypeOneHundredAndNine         AssetType = 109
	AssetTypeOneHundredAndTen          AssetType = 110
	AssetTypeOneHundredAndEleven       AssetType = 111
	AssetTypeOneHundredAndTwelve       AssetType = 112
	AssetTypeOneHundredAndThirteen     AssetType = 113
	AssetTypeOneHundredAndFourteen     AssetType = 114
	AssetTypeOneHundredAndFifteen      AssetType = 115
	AssetTypeOneHundredAndSixteen      AssetType = 116
	AssetTypeOneHundredAndSeventeen    AssetType = 117
	AssetTypeOneHundredAndEighteen     AssetType = 118
	AssetTypeOneHundredAndNineteen     AssetType = 119
	AssetTypeOneHundredAndTwenty       AssetType = 120
	AssetTypeOneHundredAndTwentyOne    AssetType = 121
	AssetTypeOneHundredAndTwentyTwo    AssetType = 122
	AssetTypeOneHundredAndTwentyThree  AssetType = 123
	AssetTypeOneHundredAndTwentyFour   AssetType = 124
	AssetTypeOneHundredAndTwentyFive   AssetType = 125
	AssetTypeOneHundredAndTwentySix    AssetType = 126
	AssetTypeOneHundredAndTwentySeven  AssetType = 127
	AssetTypeOneHundredAndTwentyEight  AssetType = 128
	AssetTypeOneHundredAndTwentyNine   AssetType = 129
	AssetTypeOneHundredAndThirty       AssetType = 130
	AssetTypeOneHundredAndThirtyOne    AssetType = 131
	AssetTypeOneHundredAndThirtyTwo    AssetType = 132
	AssetTypeOneHundredAndThirtyThree  AssetType = 133
	AssetTypeOneHundredAndThirtyFour   AssetType = 134
	AssetTypeOneHundredAndThirtyFive   AssetType = 135
	AssetTypeOneHundredAndThirtySix    AssetType = 136
	AssetTypeOneHundredAndThirtySeven  AssetType = 137
	AssetTypeOneHundredAndThirtyEight  AssetType = 138
	AssetTypeOneHundredAndThirtyNine   AssetType = 139
	AssetTypeOneHundredAndForty        AssetType = 140
	AssetTypeOneHundredAndFortyOne     AssetType = 141
	AssetTypeOneHundredAndFortyTwo     AssetType = 142
	AssetTypeOneHundredAndFortyThree   AssetType = 143
	AssetTypeOneHundredAndFortyFour    AssetType = 144
	AssetTypeOneHundredAndFortyFive    AssetType = 145
	AssetTypeOneHundredAndFortySix     AssetType = 146
	AssetTypeOneHundredAndFortySeven   AssetType = 147
	AssetTypeOneHundredAndFortyEight   AssetType = 148
	AssetTypeOneHundredAndFortyNine    AssetType = 149
	AssetTypeOneHundredAndFifty        AssetType = 150
	AssetTypeOneHundredAndFiftyOne     AssetType = 151
	AssetTypeOneHundredAndFiftyTwo     AssetType = 152
	AssetTypeOneHundredAndFiftyThree   AssetType = 153
	AssetTypeOneHundredAndFiftyFour    AssetType = 154
	AssetTypeOneHundredAndFiftyFive    AssetType = 155
	AssetTypeOneHundredAndFiftySix     AssetType = 156
	AssetTypeOneHundredAndFiftySeven   AssetType = 157
	AssetTypeOneHundredAndFiftyEight   AssetType = 158
	AssetTypeOneHundredAndFiftyNine    AssetType = 159
	AssetTypeOneHundredAndSixty        AssetType = 160
	AssetTypeOneHundredAndSixtyOne     AssetType = 161
	AssetTypeOneHundredAndSixtyTwo     AssetType = 162
	AssetTypeOneHundredAndSixtyThree   AssetType = 163
	AssetTypeOneHundredAndSixtyFour    AssetType = 164
	AssetTypeOneHundredAndSixtyFive    AssetType = 165
	AssetTypeOneHundredAndSixtySix     AssetType = 166
	AssetTypeOneHundredAndSixtySeven   AssetType = 167
	AssetTypeOneHundredAndSixtyEight   AssetType = 168
	AssetTypeOneHundredAndSixtyNine    AssetType = 169
	AssetTypeOneHundredAndSeventy      AssetType = 170
	AssetTypeOneHundredAndSeventyOne   AssetType = 171
	AssetTypeOneHundredAndSeventyTwo   AssetType = 172
	AssetTypeOneHundredAndSeventyThree AssetType = 173
	AssetTypeOneHundredAndSeventyFour  AssetType = 174
	AssetTypeOneHundredAndSeventyFive  AssetType = 175
	AssetTypeOneHundredAndSeventySix   AssetType = 176
	AssetTypeOneHundredAndSeventySeven AssetType = 177
	AssetTypeOneHundredAndSeventyEight AssetType = 178
	AssetTypeOneThousandAndOne         AssetType = 1001
)

func (e AssetType) ToPointer() *AssetType {
	return &e
}
func (e *AssetType) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		fallthrough
	case 6:
		fallthrough
	case 7:
		fallthrough
	case 8:
		fallthrough
	case 9:
		fallthrough
	case 10:
		fallthrough
	case 11:
		fallthrough
	case 12:
		fallthrough
	case 13:
		fallthrough
	case 14:
		fallthrough
	case 15:
		fallthrough
	case 16:
		fallthrough
	case 17:
		fallthrough
	case 18:
		fallthrough
	case 19:
		fallthrough
	case 20:
		fallthrough
	case 21:
		fallthrough
	case 22:
		fallthrough
	case 23:
		fallthrough
	case 24:
		fallthrough
	case 25:
		fallthrough
	case 26:
		fallthrough
	case 27:
		fallthrough
	case 29:
		fallthrough
	case 30:
		fallthrough
	case 31:
		fallthrough
	case 32:
		fallthrough
	case 33:
		fallthrough
	case 34:
		fallthrough
	case 35:
		fallthrough
	case 36:
		fallthrough
	case 37:
		fallthrough
	case 38:
		fallthrough
	case 39:
		fallthrough
	case 40:
		fallthrough
	case 41:
		fallthrough
	case 42:
		fallthrough
	case 43:
		fallthrough
	case 44:
		fallthrough
	case 45:
		fallthrough
	case 46:
		fallthrough
	case 47:
		fallthrough
	case 48:
		fallthrough
	case 49:
		fallthrough
	case 50:
		fallthrough
	case 51:
		fallthrough
	case 52:
		fallthrough
	case 53:
		fallthrough
	case 54:
		fallthrough
	case 55:
		fallthrough
	case 56:
		fallthrough
	case 57:
		fallthrough
	case 58:
		fallthrough
	case 59:
		fallthrough
	case 60:
		fallthrough
	case 61:
		fallthrough
	case 62:
		fallthrough
	case 63:
		fallthrough
	case 64:
		fallthrough
	case 65:
		fallthrough
	case 66:
		fallthrough
	case 67:
		fallthrough
	case 68:
		fallthrough
	case 69:
		fallthrough
	case 70:
		fallthrough
	case 71:
		fallthrough
	case 72:
		fallthrough
	case 73:
		fallthrough
	case 74:
		fallthrough
	case 75:
		fallthrough
	case 76:
		fallthrough
	case 77:
		fallthrough
	case 78:
		fallthrough
	case 79:
		fallthrough
	case 80:
		fallthrough
	case 81:
		fallthrough
	case 82:
		fallthrough
	case 83:
		fallthrough
	case 84:
		fallthrough
	case 85:
		fallthrough
	case 86:
		fallthrough
	case 87:
		fallthrough
	case 88:
		fallthrough
	case 89:
		fallthrough
	case 90:
		fallthrough
	case 91:
		fallthrough
	case 92:
		fallthrough
	case 93:
		fallthrough
	case 94:
		fallthrough
	case 95:
		fallthrough
	case 96:
		fallthrough
	case 97:
		fallthrough
	case 98:
		fallthrough
	case 99:
		fallthrough
	case 100:
		fallthrough
	case 101:
		fallthrough
	case 102:
		fallthrough
	case 103:
		fallthrough
	case 104:
		fallthrough
	case 105:
		fallthrough
	case 106:
		fallthrough
	case 107:
		fallthrough
	case 108:
		fallthrough
	case 109:
		fallthrough
	case 110:
		fallthrough
	case 111:
		fallthrough
	case 112:
		fallthrough
	case 113:
		fallthrough
	case 114:
		fallthrough
	case 115:
		fallthrough
	case 116:
		fallthrough
	case 117:
		fallthrough
	case 118:
		fallthrough
	case 119:
		fallthrough
	case 120:
		fallthrough
	case 121:
		fallthrough
	case 122:
		fallthrough
	case 123:
		fallthrough
	case 124:
		fallthrough
	case 125:
		fallthrough
	case 126:
		fallthrough
	case 127:
		fallthrough
	case 128:
		fallthrough
	case 129:
		fallthrough
	case 130:
		fallthrough
	case 131:
		fallthrough
	case 132:
		fallthrough
	case 133:
		fallthrough
	case 134:
		fallthrough
	case 135:
		fallthrough
	case 136:
		fallthrough
	case 137:
		fallthrough
	case 138:
		fallthrough
	case 139:
		fallthrough
	case 140:
		fallthrough
	case 141:
		fallthrough
	case 142:
		fallthrough
	case 143:
		fallthrough
	case 144:
		fallthrough
	case 145:
		fallthrough
	case 146:
		fallthrough
	case 147:
		fallthrough
	case 148:
		fallthrough
	case 149:
		fallthrough
	case 150:
		fallthrough
	case 151:
		fallthrough
	case 152:
		fallthrough
	case 153:
		fallthrough
	case 154:
		fallthrough
	case 155:
		fallthrough
	case 156:
		fallthrough
	case 157:
		fallthrough
	case 158:
		fallthrough
	case 159:
		fallthrough
	case 160:
		fallthrough
	case 161:
		fallthrough
	case 162:
		fallthrough
	case 163:
		fallthrough
	case 164:
		fallthrough
	case 165:
		fallthrough
	case 166:
		fallthrough
	case 167:
		fallthrough
	case 168:
		fallthrough
	case 169:
		fallthrough
	case 170:
		fallthrough
	case 171:
		fallthrough
	case 172:
		fallthrough
	case 173:
		fallthrough
	case 174:
		fallthrough
	case 175:
		fallthrough
	case 176:
		fallthrough
	case 177:
		fallthrough
	case 178:
		fallthrough
	case 1001:
		*e = AssetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssetType: %v", v)
	}
}
