// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AssetIDSearch struct {
	AssetID *string `json:"assetId,omitempty"`
}

func (a *AssetIDSearch) GetAssetID() *string {
	if a == nil {
		return nil
	}
	return a.AssetID
}
