// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CustomGroupBody struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// members id
	MembersID []string `json:"membersId,omitempty"`
}

func (o *CustomGroupBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CustomGroupBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CustomGroupBody) GetMembersID() []string {
	if o == nil {
		return nil
	}
	return o.MembersID
}
