// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CustomGroupMembersBody struct {
	// members id
	MembersID []string `json:"membersId"`
}

func (c *CustomGroupMembersBody) GetMembersID() []string {
	if c == nil {
		return []string{}
	}
	return c.MembersID
}
