// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CustomGroupAddedBy struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (c *CustomGroupAddedBy) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomGroupAddedBy) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

type CustomGroup struct {
	// Epoch Millis
	CreatedAt           *int64  `json:"createdAt,omitempty"`
	Description         *string `json:"description,omitempty"`
	DirectMembersCount  *int64  `json:"directMembersCount,omitempty"`
	Domain              *string `json:"domain,omitempty"`
	GUID                *string `json:"guid,omitempty"`
	HasProtectionPolicy *bool   `json:"hasProtectionPolicy,omitempty"`
	ID                  *string `json:"id,omitempty"`
	Name                *string `json:"name,omitempty"`
	PrincipalName       *string `json:"principalName,omitempty"`
	Role                *int64  `json:"role,omitempty"`
	Sid                 *string `json:"sid,omitempty"`
	// Epoch Millis
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
	// Epoch Millis
	AddedAt *int64              `json:"addedAt,omitempty"`
	AddedBy *CustomGroupAddedBy `json:"addedBy,omitempty"`
}

func (c *CustomGroup) GetCreatedAt() *int64 {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CustomGroup) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomGroup) GetDirectMembersCount() *int64 {
	if c == nil {
		return nil
	}
	return c.DirectMembersCount
}

func (c *CustomGroup) GetDomain() *string {
	if c == nil {
		return nil
	}
	return c.Domain
}

func (c *CustomGroup) GetGUID() *string {
	if c == nil {
		return nil
	}
	return c.GUID
}

func (c *CustomGroup) GetHasProtectionPolicy() *bool {
	if c == nil {
		return nil
	}
	return c.HasProtectionPolicy
}

func (c *CustomGroup) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomGroup) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomGroup) GetPrincipalName() *string {
	if c == nil {
		return nil
	}
	return c.PrincipalName
}

func (c *CustomGroup) GetRole() *int64 {
	if c == nil {
		return nil
	}
	return c.Role
}

func (c *CustomGroup) GetSid() *string {
	if c == nil {
		return nil
	}
	return c.Sid
}

func (c *CustomGroup) GetUpdatedAt() *int64 {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CustomGroup) GetAddedAt() *int64 {
	if c == nil {
		return nil
	}
	return c.AddedAt
}

func (c *CustomGroup) GetAddedBy() *CustomGroupAddedBy {
	if c == nil {
		return nil
	}
	return c.AddedBy
}
