// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CustomGroupResponse struct {
	Entity *CustomGroup `json:"entity,omitempty"`
}

func (o *CustomGroupResponse) GetEntity() *CustomGroup {
	if o == nil {
		return nil
	}
	return o.Entity
}
