// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Conditions - Defines dynamic selection criteria for group membership
type Conditions struct {
	NamePatterns   []string `json:"namePatterns,omitempty"`
	OsTypes        []int64  `json:"osTypes,omitempty"`
	OsNamePatterns []string `json:"osNamePatterns,omitempty"`
	AssetTypes     []int64  `json:"assetTypes,omitempty"`
}

func (c *Conditions) GetNamePatterns() []string {
	if c == nil {
		return nil
	}
	return c.NamePatterns
}

func (c *Conditions) GetOsTypes() []int64 {
	if c == nil {
		return nil
	}
	return c.OsTypes
}

func (c *Conditions) GetOsNamePatterns() []string {
	if c == nil {
		return nil
	}
	return c.OsNamePatterns
}

func (c *Conditions) GetAssetTypes() []int64 {
	if c == nil {
		return nil
	}
	return c.AssetTypes
}

type CustomGroupBody struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// members id
	MembersID []string `json:"membersId,omitempty"`
	// Defines dynamic selection criteria for group membership
	Conditions *Conditions `json:"conditions,omitempty"`
}

func (c *CustomGroupBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomGroupBody) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomGroupBody) GetMembersID() []string {
	if c == nil {
		return nil
	}
	return c.MembersID
}

func (c *CustomGroupBody) GetConditions() *Conditions {
	if c == nil {
		return nil
	}
	return c.Conditions
}
