// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Error - Bad Request
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *Error) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
