// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GroupBasicInfo struct {
	Domain                      *string `json:"domain,omitempty"`
	GUID                        *string `json:"guid,omitempty"`
	HasNetworkProtectionPolicy  *bool   `json:"hasNetworkProtectionPolicy,omitempty"`
	HasIdentityProtectionPolicy *bool   `json:"hasIdentityProtectionPolicy,omitempty"`
	ID                          *string `json:"id,omitempty"`
	Name                        *string `json:"name,omitempty"`
	Sid                         *string `json:"sid,omitempty"`
}

func (o *GroupBasicInfo) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *GroupBasicInfo) GetGUID() *string {
	if o == nil {
		return nil
	}
	return o.GUID
}

func (o *GroupBasicInfo) GetHasNetworkProtectionPolicy() *bool {
	if o == nil {
		return nil
	}
	return o.HasNetworkProtectionPolicy
}

func (o *GroupBasicInfo) GetHasIdentityProtectionPolicy() *bool {
	if o == nil {
		return nil
	}
	return o.HasIdentityProtectionPolicy
}

func (o *GroupBasicInfo) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GroupBasicInfo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GroupBasicInfo) GetSid() *string {
	if o == nil {
		return nil
	}
	return o.Sid
}
