// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/internal/utils"
)

type AddedBy struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (a AddedBy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddedBy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddedBy) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AddedBy) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

type Group struct {
	// Epoch Millis
	CreatedAt           *int64  `json:"createdAt,omitempty"`
	Description         *string `json:"description,omitempty"`
	DirectMembersCount  *int64  `json:"directMembersCount,omitempty"`
	Domain              *string `json:"domain,omitempty"`
	ExternalID          *string `json:"externalId,omitempty"`
	GUID                *string `json:"guid,omitempty"`
	HasProtectionPolicy *bool   `json:"hasProtectionPolicy,omitempty"`
	ID                  *string `json:"id,omitempty"`
	Name                *string `json:"name,omitempty"`
	PrincipalName       *string `json:"principalName,omitempty"`
	Role                *int    `json:"role,omitempty"`
	Sid                 *string `json:"sid,omitempty"`
	// Epoch Millis
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
	// Epoch Millis
	AddedAt *int64   `json:"addedAt,omitempty"`
	AddedBy *AddedBy `json:"addedBy,omitempty"`
}

func (g Group) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Group) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Group) GetCreatedAt() *int64 {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *Group) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *Group) GetDirectMembersCount() *int64 {
	if g == nil {
		return nil
	}
	return g.DirectMembersCount
}

func (g *Group) GetDomain() *string {
	if g == nil {
		return nil
	}
	return g.Domain
}

func (g *Group) GetExternalID() *string {
	if g == nil {
		return nil
	}
	return g.ExternalID
}

func (g *Group) GetGUID() *string {
	if g == nil {
		return nil
	}
	return g.GUID
}

func (g *Group) GetHasProtectionPolicy() *bool {
	if g == nil {
		return nil
	}
	return g.HasProtectionPolicy
}

func (g *Group) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *Group) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *Group) GetPrincipalName() *string {
	if g == nil {
		return nil
	}
	return g.PrincipalName
}

func (g *Group) GetRole() *int {
	if g == nil {
		return nil
	}
	return g.Role
}

func (g *Group) GetSid() *string {
	if g == nil {
		return nil
	}
	return g.Sid
}

func (g *Group) GetUpdatedAt() *int64 {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}

func (g *Group) GetAddedAt() *int64 {
	if g == nil {
		return nil
	}
	return g.AddedAt
}

func (g *Group) GetAddedBy() *AddedBy {
	if g == nil {
		return nil
	}
	return g.AddedBy
}
