// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IdentityProtectionCategory - * '0' - Unspecified
// * '1' - Locally
// * '2' - Network
// * '3' - Batch
// * '4' - Service
// * '5' - RDP
type IdentityProtectionCategory int

const (
	IdentityProtectionCategoryZero  IdentityProtectionCategory = 0
	IdentityProtectionCategoryOne   IdentityProtectionCategory = 1
	IdentityProtectionCategoryTwo   IdentityProtectionCategory = 2
	IdentityProtectionCategoryThree IdentityProtectionCategory = 3
	IdentityProtectionCategoryFour  IdentityProtectionCategory = 4
	IdentityProtectionCategoryFive  IdentityProtectionCategory = 5
)

func (e IdentityProtectionCategory) ToPointer() *IdentityProtectionCategory {
	return &e
}
func (e *IdentityProtectionCategory) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		*e = IdentityProtectionCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IdentityProtectionCategory: %v", v)
	}
}
