// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type IDNamePair struct {
	// EntityId
	ID *string `json:"id,omitempty"`
	// Entity Name
	Name *string `json:"name,omitempty"`
}

func (i *IDNamePair) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IDNamePair) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}
