// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type IDNamePair struct {
	// EntityId
	ID *string `json:"id,omitempty"`
	// Entity Name
	Name *string `json:"name,omitempty"`
}

func (o *IDNamePair) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *IDNamePair) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
