// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MfaMethods - * '1' - SMS
// * '2' - Email
// * '3' - Duo
// * '4' - Browser
// * '5' - No MFA
// * '6' - MicrosoftAuthenticator
// * '7' - Okta
type MfaMethods int

const (
	MfaMethodsOne   MfaMethods = 1
	MfaMethodsTwo   MfaMethods = 2
	MfaMethodsThree MfaMethods = 3
	MfaMethodsFour  MfaMethods = 4
	MfaMethodsFive  MfaMethods = 5
	MfaMethodsSix   MfaMethods = 6
	MfaMethodsSeven MfaMethods = 7
)

func (e MfaMethods) ToPointer() *MfaMethods {
	return &e
}
func (e *MfaMethods) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		fallthrough
	case 6:
		fallthrough
	case 7:
		*e = MfaMethods(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MfaMethods: %v", v)
	}
}
