// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Protocol - * '0' - HOPOPT
// * '1' - ICMP
// * '2' - IGMP
// * '3' - GGP
// * '4' - IPv4
// * '5' - ST
// * '6' - TCP
// * '7' - CBT
// * '8' - EGP
// * '9' - IGP
// * '10' - BBN-RCC-MON
// * '11' - NVP-II
// * '12' - PUP
// * '13' - ARGUS
// * '14' - EMCON
// * '15' - XNET
// * '16' - CHAOS
// * '17' - UDP
// * '18' - MUX
// * '19' - DCN-MEAS
// * '20' - HMP
// * '21' - PRM
// * '22' - XNS-IDP
// * '23' - TRUNK-1
// * '24' - TRUNK-2
// * '25' - LEAF-1
// * '26' - LEAF-2
// * '27' - RDP
// * '28' - IRTP
// * '29' - ISO-TP4
// * '30' - NETBLT
// * '31' - MFE-NSP
// * '32' - MERIT-INP
// * '33' - DCCP
// * '34' - 3PC
// * '35' - IDPR
// * '36' - XTP
// * '37' - DDP
// * '38' - IDPR-CMTP
// * '39' - TP++
// * '40' - IL
// * '41' - Embedded
// * '42' - SDRP
// * '43' - IPv6RoutingHeader
// * '44' - IPv6FragmentHeader
// * '45' - IDRP
// * '46' - RSVP
// * '47' - GRE
// * '48' - DSR
// * '49' - BNA
// * '50' - ESP
// * '51' - AH
// * '52' - I-NLSP
// * '53' - SwIPe
// * '54' - NARP
// * '55' - MOBILE
// * '56' - TLSP
// * '57' - SKIP
// * '58' - ICMPv6
// * '59' - IPv6NonExtHeader
// * '60' - IPv6DestinationOptions
// * '61' - Host-interanl
// * '62' - CFTP
// * '63' - local-network
// * '64' - SAT-EXPAK
// * '65' - KRYPTOLAN
// * '66' - RVD
// * '67' - IPPC
// * '68' - distributed-file-system
// * '69' - SAT-MON
// * '70' - VISA
// * '71' - IPCU
// * '72' - CPNX
// * '73' - CPHB
// * '74' - WSN
// * '75' - PVP
// * '76' - BR-SAT-MON
// * '77' - ND
// * '78' - WB-MON
// * '79' - WB-EXPAK
// * '80' - ISO-IP
// * '81' - VMTP
// * '82' - SECURE-VMTP
// * '83' - VINES
// * '84' - IPTM
// * '85' - NSFNET-IGP
// * '86' - DGP
// * '87' - TCF
// * '88' - EIGRP
// * '89' - OSPF
// * '90' - Sprite-RPC
// * '91' - LARP
// * '92' - MTP
// * '93' - AX.25
// * '94' - OS
// * '95' - MICP
// * '96' - SCC-SP
// * '97' - ETHERIP
// * '98' - ENCAP
// * '99' - private-encryption
// * '100' - GMTP
// * '101' - IFMP
// * '102' - PNNI
// * '103' - PIM
// * '104' - ARIS
// * '105' - SCPS
// * '106' - QNX
// * '107' - A/N
// * '108' - IPComp
// * '109' - SNP
// * '110' - Compaq-Peer
// * '111' - IPX-in-IP
// * '112' - VRRP
// * '113' - PGM
// * '114' - 0-hop
// * '115' - L2TP
// * '116' - DDX
// * '117' - IATP
// * '118' - STP
// * '119' - SRP
// * '120' - UTI
// * '121' - SMP
// * '122' - SM
// * '123' - PTP
// * '124' - IS-IS-over-IPv4
// * '125' - FIRE
// * '126' - CRTP
// * '127' - CRUDP
// * '128' - SSCOPMCE
// * '129' - IPLT
// * '130' - SPS
// * '131' - PIPE
// * '132' - SCTP
// * '133' - FC
// * '134' - RSVP-E2E-IGNORE
// * '135' - Mobility-Header
// * '136' - UDPLite
// * '137' - MPLS-in-IP
// * '138' - manet
// * '139' - HIP
// * '140' - Shim6
// * '141' - WESP
// * '142' - ROHC
// * '143' - Ethernet
// * '144' - 144 (custom)
// * '145' - 145 (custom)
// * '146' - 146 (custom)
// * '147' - 147 (custom)
// * '148' - 148 (custom)
// * '149' - 149 (custom)
// * '150' - 150 (custom)
// * '151' - 151 (custom)
// * '152' - 152 (custom)
// * '153' - 153 (custom)
// * '154' - 154 (custom)
// * '155' - 155 (custom)
// * '156' - 156 (custom)
// * '157' - 157 (custom)
// * '158' - 158 (custom)
// * '159' - 159 (custom)
// * '160' - 160 (custom)
// * '161' - 161 (custom)
// * '162' - 162 (custom)
// * '163' - 163 (custom)
// * '164' - 164 (custom)
// * '165' - 165 (custom)
// * '166' - 166 (custom)
// * '167' - 167 (custom)
// * '168' - 168 (custom)
// * '169' - 169 (custom)
// * '170' - 170 (custom)
// * '171' - 171 (custom)
// * '172' - 172 (custom)
// * '173' - 173 (custom)
// * '174' - 174 (custom)
// * '175' - 175 (custom)
// * '176' - 176 (custom)
// * '177' - 177 (custom)
// * '178' - 178 (custom)
// * '179' - 179 (custom)
// * '180' - 180 (custom)
// * '181' - 181 (custom)
// * '182' - 182 (custom)
// * '183' - 183 (custom)
// * '184' - 184 (custom)
// * '185' - 185 (custom)
// * '186' - 186 (custom)
// * '187' - 187 (custom)
// * '188' - 188 (custom)
// * '189' - 189 (custom)
// * '190' - 190 (custom)
// * '191' - 191 (custom)
// * '192' - 192 (custom)
// * '193' - 193 (custom)
// * '194' - 194 (custom)
// * '195' - 195 (custom)
// * '196' - 196 (custom)
// * '197' - 197 (custom)
// * '198' - 198 (custom)
// * '199' - 199 (custom)
// * '200' - 200 (custom)
// * '201' - 201 (custom)
// * '202' - 202 (custom)
// * '203' - 203 (custom)
// * '204' - 204 (custom)
// * '205' - 205 (custom)
// * '206' - 206 (custom)
// * '207' - 207 (custom)
// * '208' - 208 (custom)
// * '209' - 209 (custom)
// * '210' - 210 (custom)
// * '211' - 211 (custom)
// * '212' - 212 (custom)
// * '213' - 213 (custom)
// * '214' - 214 (custom)
// * '215' - 215 (custom)
// * '216' - 216 (custom)
// * '217' - 217 (custom)
// * '218' - 218 (custom)
// * '219' - 219 (custom)
// * '220' - 220 (custom)
// * '221' - 221 (custom)
// * '222' - 222 (custom)
// * '223' - 223 (custom)
// * '224' - 224 (custom)
// * '225' - 225 (custom)
// * '226' - 226 (custom)
// * '227' - 227 (custom)
// * '228' - 228 (custom)
// * '229' - 229 (custom)
// * '230' - 230 (custom)
// * '231' - 231 (custom)
// * '232' - 232 (custom)
// * '233' - 233 (custom)
// * '234' - 234 (custom)
// * '235' - 235 (custom)
// * '236' - 236 (custom)
// * '237' - 237 (custom)
// * '238' - 238 (custom)
// * '239' - 239 (custom)
// * '240' - 240 (custom)
// * '241' - 241 (custom)
// * '242' - 242 (custom)
// * '243' - 243 (custom)
// * '244' - 244 (custom)
// * '245' - 245 (custom)
// * '246' - 246 (custom)
// * '247' - 247 (custom)
// * '248' - 248 (custom)
// * '249' - 249 (custom)
// * '250' - 250 (custom)
// * '251' - 251 (custom)
// * '252' - 252 (custom)
// * '253' - 253 (custom)
// * '254' - 254 (custom)
// * '255' - Raw
// * '256' - Any
type Protocol int

const (
	ProtocolZero                      Protocol = 0
	ProtocolOne                       Protocol = 1
	ProtocolTwo                       Protocol = 2
	ProtocolThree                     Protocol = 3
	ProtocolFour                      Protocol = 4
	ProtocolFive                      Protocol = 5
	ProtocolSix                       Protocol = 6
	ProtocolSeven                     Protocol = 7
	ProtocolEight                     Protocol = 8
	ProtocolNine                      Protocol = 9
	ProtocolTen                       Protocol = 10
	ProtocolEleven                    Protocol = 11
	ProtocolTwelve                    Protocol = 12
	ProtocolThirteen                  Protocol = 13
	ProtocolFourteen                  Protocol = 14
	ProtocolFifteen                   Protocol = 15
	ProtocolSixteen                   Protocol = 16
	ProtocolSeventeen                 Protocol = 17
	ProtocolEighteen                  Protocol = 18
	ProtocolNineteen                  Protocol = 19
	ProtocolTwenty                    Protocol = 20
	ProtocolTwentyOne                 Protocol = 21
	ProtocolTwentyTwo                 Protocol = 22
	ProtocolTwentyThree               Protocol = 23
	ProtocolTwentyFour                Protocol = 24
	ProtocolTwentyFive                Protocol = 25
	ProtocolTwentySix                 Protocol = 26
	ProtocolTwentySeven               Protocol = 27
	ProtocolTwentyEight               Protocol = 28
	ProtocolTwentyNine                Protocol = 29
	ProtocolThirty                    Protocol = 30
	ProtocolThirtyOne                 Protocol = 31
	ProtocolThirtyTwo                 Protocol = 32
	ProtocolThirtyThree               Protocol = 33
	ProtocolThirtyFour                Protocol = 34
	ProtocolThirtyFive                Protocol = 35
	ProtocolThirtySix                 Protocol = 36
	ProtocolThirtySeven               Protocol = 37
	ProtocolThirtyEight               Protocol = 38
	ProtocolThirtyNine                Protocol = 39
	ProtocolForty                     Protocol = 40
	ProtocolFortyOne                  Protocol = 41
	ProtocolFortyTwo                  Protocol = 42
	ProtocolFortyThree                Protocol = 43
	ProtocolFortyFour                 Protocol = 44
	ProtocolFortyFive                 Protocol = 45
	ProtocolFortySix                  Protocol = 46
	ProtocolFortySeven                Protocol = 47
	ProtocolFortyEight                Protocol = 48
	ProtocolFortyNine                 Protocol = 49
	ProtocolFifty                     Protocol = 50
	ProtocolFiftyOne                  Protocol = 51
	ProtocolFiftyTwo                  Protocol = 52
	ProtocolFiftyThree                Protocol = 53
	ProtocolFiftyFour                 Protocol = 54
	ProtocolFiftyFive                 Protocol = 55
	ProtocolFiftySix                  Protocol = 56
	ProtocolFiftySeven                Protocol = 57
	ProtocolFiftyEight                Protocol = 58
	ProtocolFiftyNine                 Protocol = 59
	ProtocolSixty                     Protocol = 60
	ProtocolSixtyOne                  Protocol = 61
	ProtocolSixtyTwo                  Protocol = 62
	ProtocolSixtyThree                Protocol = 63
	ProtocolSixtyFour                 Protocol = 64
	ProtocolSixtyFive                 Protocol = 65
	ProtocolSixtySix                  Protocol = 66
	ProtocolSixtySeven                Protocol = 67
	ProtocolSixtyEight                Protocol = 68
	ProtocolSixtyNine                 Protocol = 69
	ProtocolSeventy                   Protocol = 70
	ProtocolSeventyOne                Protocol = 71
	ProtocolSeventyTwo                Protocol = 72
	ProtocolSeventyThree              Protocol = 73
	ProtocolSeventyFour               Protocol = 74
	ProtocolSeventyFive               Protocol = 75
	ProtocolSeventySix                Protocol = 76
	ProtocolSeventySeven              Protocol = 77
	ProtocolSeventyEight              Protocol = 78
	ProtocolSeventyNine               Protocol = 79
	ProtocolEighty                    Protocol = 80
	ProtocolEightyOne                 Protocol = 81
	ProtocolEightyTwo                 Protocol = 82
	ProtocolEightyThree               Protocol = 83
	ProtocolEightyFour                Protocol = 84
	ProtocolEightyFive                Protocol = 85
	ProtocolEightySix                 Protocol = 86
	ProtocolEightySeven               Protocol = 87
	ProtocolEightyEight               Protocol = 88
	ProtocolEightyNine                Protocol = 89
	ProtocolNinety                    Protocol = 90
	ProtocolNinetyOne                 Protocol = 91
	ProtocolNinetyTwo                 Protocol = 92
	ProtocolNinetyThree               Protocol = 93
	ProtocolNinetyFour                Protocol = 94
	ProtocolNinetyFive                Protocol = 95
	ProtocolNinetySix                 Protocol = 96
	ProtocolNinetySeven               Protocol = 97
	ProtocolNinetyEight               Protocol = 98
	ProtocolNinetyNine                Protocol = 99
	ProtocolOneHundred                Protocol = 100
	ProtocolOneHundredAndOne          Protocol = 101
	ProtocolOneHundredAndTwo          Protocol = 102
	ProtocolOneHundredAndThree        Protocol = 103
	ProtocolOneHundredAndFour         Protocol = 104
	ProtocolOneHundredAndFive         Protocol = 105
	ProtocolOneHundredAndSix          Protocol = 106
	ProtocolOneHundredAndSeven        Protocol = 107
	ProtocolOneHundredAndEight        Protocol = 108
	ProtocolOneHundredAndNine         Protocol = 109
	ProtocolOneHundredAndTen          Protocol = 110
	ProtocolOneHundredAndEleven       Protocol = 111
	ProtocolOneHundredAndTwelve       Protocol = 112
	ProtocolOneHundredAndThirteen     Protocol = 113
	ProtocolOneHundredAndFourteen     Protocol = 114
	ProtocolOneHundredAndFifteen      Protocol = 115
	ProtocolOneHundredAndSixteen      Protocol = 116
	ProtocolOneHundredAndSeventeen    Protocol = 117
	ProtocolOneHundredAndEighteen     Protocol = 118
	ProtocolOneHundredAndNineteen     Protocol = 119
	ProtocolOneHundredAndTwenty       Protocol = 120
	ProtocolOneHundredAndTwentyOne    Protocol = 121
	ProtocolOneHundredAndTwentyTwo    Protocol = 122
	ProtocolOneHundredAndTwentyThree  Protocol = 123
	ProtocolOneHundredAndTwentyFour   Protocol = 124
	ProtocolOneHundredAndTwentyFive   Protocol = 125
	ProtocolOneHundredAndTwentySix    Protocol = 126
	ProtocolOneHundredAndTwentySeven  Protocol = 127
	ProtocolOneHundredAndTwentyEight  Protocol = 128
	ProtocolOneHundredAndTwentyNine   Protocol = 129
	ProtocolOneHundredAndThirty       Protocol = 130
	ProtocolOneHundredAndThirtyOne    Protocol = 131
	ProtocolOneHundredAndThirtyTwo    Protocol = 132
	ProtocolOneHundredAndThirtyThree  Protocol = 133
	ProtocolOneHundredAndThirtyFour   Protocol = 134
	ProtocolOneHundredAndThirtyFive   Protocol = 135
	ProtocolOneHundredAndThirtySix    Protocol = 136
	ProtocolOneHundredAndThirtySeven  Protocol = 137
	ProtocolOneHundredAndThirtyEight  Protocol = 138
	ProtocolOneHundredAndThirtyNine   Protocol = 139
	ProtocolOneHundredAndForty        Protocol = 140
	ProtocolOneHundredAndFortyOne     Protocol = 141
	ProtocolOneHundredAndFortyTwo     Protocol = 142
	ProtocolOneHundredAndFortyThree   Protocol = 143
	ProtocolOneHundredAndFortyFour    Protocol = 144
	ProtocolOneHundredAndFortyFive    Protocol = 145
	ProtocolOneHundredAndFortySix     Protocol = 146
	ProtocolOneHundredAndFortySeven   Protocol = 147
	ProtocolOneHundredAndFortyEight   Protocol = 148
	ProtocolOneHundredAndFortyNine    Protocol = 149
	ProtocolOneHundredAndFifty        Protocol = 150
	ProtocolOneHundredAndFiftyOne     Protocol = 151
	ProtocolOneHundredAndFiftyTwo     Protocol = 152
	ProtocolOneHundredAndFiftyThree   Protocol = 153
	ProtocolOneHundredAndFiftyFour    Protocol = 154
	ProtocolOneHundredAndFiftyFive    Protocol = 155
	ProtocolOneHundredAndFiftySix     Protocol = 156
	ProtocolOneHundredAndFiftySeven   Protocol = 157
	ProtocolOneHundredAndFiftyEight   Protocol = 158
	ProtocolOneHundredAndFiftyNine    Protocol = 159
	ProtocolOneHundredAndSixty        Protocol = 160
	ProtocolOneHundredAndSixtyOne     Protocol = 161
	ProtocolOneHundredAndSixtyTwo     Protocol = 162
	ProtocolOneHundredAndSixtyThree   Protocol = 163
	ProtocolOneHundredAndSixtyFour    Protocol = 164
	ProtocolOneHundredAndSixtyFive    Protocol = 165
	ProtocolOneHundredAndSixtySix     Protocol = 166
	ProtocolOneHundredAndSixtySeven   Protocol = 167
	ProtocolOneHundredAndSixtyEight   Protocol = 168
	ProtocolOneHundredAndSixtyNine    Protocol = 169
	ProtocolOneHundredAndSeventy      Protocol = 170
	ProtocolOneHundredAndSeventyOne   Protocol = 171
	ProtocolOneHundredAndSeventyTwo   Protocol = 172
	ProtocolOneHundredAndSeventyThree Protocol = 173
	ProtocolOneHundredAndSeventyFour  Protocol = 174
	ProtocolOneHundredAndSeventyFive  Protocol = 175
	ProtocolOneHundredAndSeventySix   Protocol = 176
	ProtocolOneHundredAndSeventySeven Protocol = 177
	ProtocolOneHundredAndSeventyEight Protocol = 178
	ProtocolOneHundredAndSeventyNine  Protocol = 179
	ProtocolOneHundredAndEighty       Protocol = 180
	ProtocolOneHundredAndEightyOne    Protocol = 181
	ProtocolOneHundredAndEightyTwo    Protocol = 182
	ProtocolOneHundredAndEightyThree  Protocol = 183
	ProtocolOneHundredAndEightyFour   Protocol = 184
	ProtocolOneHundredAndEightyFive   Protocol = 185
	ProtocolOneHundredAndEightySix    Protocol = 186
	ProtocolOneHundredAndEightySeven  Protocol = 187
	ProtocolOneHundredAndEightyEight  Protocol = 188
	ProtocolOneHundredAndEightyNine   Protocol = 189
	ProtocolOneHundredAndNinety       Protocol = 190
	ProtocolOneHundredAndNinetyOne    Protocol = 191
	ProtocolOneHundredAndNinetyTwo    Protocol = 192
	ProtocolOneHundredAndNinetyThree  Protocol = 193
	ProtocolOneHundredAndNinetyFour   Protocol = 194
	ProtocolOneHundredAndNinetyFive   Protocol = 195
	ProtocolOneHundredAndNinetySix    Protocol = 196
	ProtocolOneHundredAndNinetySeven  Protocol = 197
	ProtocolOneHundredAndNinetyEight  Protocol = 198
	ProtocolOneHundredAndNinetyNine   Protocol = 199
	ProtocolTwoHundred                Protocol = 200
	ProtocolTwoHundredAndOne          Protocol = 201
	ProtocolTwoHundredAndTwo          Protocol = 202
	ProtocolTwoHundredAndThree        Protocol = 203
	ProtocolTwoHundredAndFour         Protocol = 204
	ProtocolTwoHundredAndFive         Protocol = 205
	ProtocolTwoHundredAndSix          Protocol = 206
	ProtocolTwoHundredAndSeven        Protocol = 207
	ProtocolTwoHundredAndEight        Protocol = 208
	ProtocolTwoHundredAndNine         Protocol = 209
	ProtocolTwoHundredAndTen          Protocol = 210
	ProtocolTwoHundredAndEleven       Protocol = 211
	ProtocolTwoHundredAndTwelve       Protocol = 212
	ProtocolTwoHundredAndThirteen     Protocol = 213
	ProtocolTwoHundredAndFourteen     Protocol = 214
	ProtocolTwoHundredAndFifteen      Protocol = 215
	ProtocolTwoHundredAndSixteen      Protocol = 216
	ProtocolTwoHundredAndSeventeen    Protocol = 217
	ProtocolTwoHundredAndEighteen     Protocol = 218
	ProtocolTwoHundredAndNineteen     Protocol = 219
	ProtocolTwoHundredAndTwenty       Protocol = 220
	ProtocolTwoHundredAndTwentyOne    Protocol = 221
	ProtocolTwoHundredAndTwentyTwo    Protocol = 222
	ProtocolTwoHundredAndTwentyThree  Protocol = 223
	ProtocolTwoHundredAndTwentyFour   Protocol = 224
	ProtocolTwoHundredAndTwentyFive   Protocol = 225
	ProtocolTwoHundredAndTwentySix    Protocol = 226
	ProtocolTwoHundredAndTwentySeven  Protocol = 227
	ProtocolTwoHundredAndTwentyEight  Protocol = 228
	ProtocolTwoHundredAndTwentyNine   Protocol = 229
	ProtocolTwoHundredAndThirty       Protocol = 230
	ProtocolTwoHundredAndThirtyOne    Protocol = 231
	ProtocolTwoHundredAndThirtyTwo    Protocol = 232
	ProtocolTwoHundredAndThirtyThree  Protocol = 233
	ProtocolTwoHundredAndThirtyFour   Protocol = 234
	ProtocolTwoHundredAndThirtyFive   Protocol = 235
	ProtocolTwoHundredAndThirtySix    Protocol = 236
	ProtocolTwoHundredAndThirtySeven  Protocol = 237
	ProtocolTwoHundredAndThirtyEight  Protocol = 238
	ProtocolTwoHundredAndThirtyNine   Protocol = 239
	ProtocolTwoHundredAndForty        Protocol = 240
	ProtocolTwoHundredAndFortyOne     Protocol = 241
	ProtocolTwoHundredAndFortyTwo     Protocol = 242
	ProtocolTwoHundredAndFortyThree   Protocol = 243
	ProtocolTwoHundredAndFortyFour    Protocol = 244
	ProtocolTwoHundredAndFortyFive    Protocol = 245
	ProtocolTwoHundredAndFortySix     Protocol = 246
	ProtocolTwoHundredAndFortySeven   Protocol = 247
	ProtocolTwoHundredAndFortyEight   Protocol = 248
	ProtocolTwoHundredAndFortyNine    Protocol = 249
	ProtocolTwoHundredAndFifty        Protocol = 250
	ProtocolTwoHundredAndFiftyOne     Protocol = 251
	ProtocolTwoHundredAndFiftyTwo     Protocol = 252
	ProtocolTwoHundredAndFiftyThree   Protocol = 253
	ProtocolTwoHundredAndFiftyFour    Protocol = 254
	ProtocolTwoHundredAndFiftyFive    Protocol = 255
	ProtocolTwoHundredAndFiftySix     Protocol = 256
)

func (e Protocol) ToPointer() *Protocol {
	return &e
}
func (e *Protocol) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		fallthrough
	case 6:
		fallthrough
	case 7:
		fallthrough
	case 8:
		fallthrough
	case 9:
		fallthrough
	case 10:
		fallthrough
	case 11:
		fallthrough
	case 12:
		fallthrough
	case 13:
		fallthrough
	case 14:
		fallthrough
	case 15:
		fallthrough
	case 16:
		fallthrough
	case 17:
		fallthrough
	case 18:
		fallthrough
	case 19:
		fallthrough
	case 20:
		fallthrough
	case 21:
		fallthrough
	case 22:
		fallthrough
	case 23:
		fallthrough
	case 24:
		fallthrough
	case 25:
		fallthrough
	case 26:
		fallthrough
	case 27:
		fallthrough
	case 28:
		fallthrough
	case 29:
		fallthrough
	case 30:
		fallthrough
	case 31:
		fallthrough
	case 32:
		fallthrough
	case 33:
		fallthrough
	case 34:
		fallthrough
	case 35:
		fallthrough
	case 36:
		fallthrough
	case 37:
		fallthrough
	case 38:
		fallthrough
	case 39:
		fallthrough
	case 40:
		fallthrough
	case 41:
		fallthrough
	case 42:
		fallthrough
	case 43:
		fallthrough
	case 44:
		fallthrough
	case 45:
		fallthrough
	case 46:
		fallthrough
	case 47:
		fallthrough
	case 48:
		fallthrough
	case 49:
		fallthrough
	case 50:
		fallthrough
	case 51:
		fallthrough
	case 52:
		fallthrough
	case 53:
		fallthrough
	case 54:
		fallthrough
	case 55:
		fallthrough
	case 56:
		fallthrough
	case 57:
		fallthrough
	case 58:
		fallthrough
	case 59:
		fallthrough
	case 60:
		fallthrough
	case 61:
		fallthrough
	case 62:
		fallthrough
	case 63:
		fallthrough
	case 64:
		fallthrough
	case 65:
		fallthrough
	case 66:
		fallthrough
	case 67:
		fallthrough
	case 68:
		fallthrough
	case 69:
		fallthrough
	case 70:
		fallthrough
	case 71:
		fallthrough
	case 72:
		fallthrough
	case 73:
		fallthrough
	case 74:
		fallthrough
	case 75:
		fallthrough
	case 76:
		fallthrough
	case 77:
		fallthrough
	case 78:
		fallthrough
	case 79:
		fallthrough
	case 80:
		fallthrough
	case 81:
		fallthrough
	case 82:
		fallthrough
	case 83:
		fallthrough
	case 84:
		fallthrough
	case 85:
		fallthrough
	case 86:
		fallthrough
	case 87:
		fallthrough
	case 88:
		fallthrough
	case 89:
		fallthrough
	case 90:
		fallthrough
	case 91:
		fallthrough
	case 92:
		fallthrough
	case 93:
		fallthrough
	case 94:
		fallthrough
	case 95:
		fallthrough
	case 96:
		fallthrough
	case 97:
		fallthrough
	case 98:
		fallthrough
	case 99:
		fallthrough
	case 100:
		fallthrough
	case 101:
		fallthrough
	case 102:
		fallthrough
	case 103:
		fallthrough
	case 104:
		fallthrough
	case 105:
		fallthrough
	case 106:
		fallthrough
	case 107:
		fallthrough
	case 108:
		fallthrough
	case 109:
		fallthrough
	case 110:
		fallthrough
	case 111:
		fallthrough
	case 112:
		fallthrough
	case 113:
		fallthrough
	case 114:
		fallthrough
	case 115:
		fallthrough
	case 116:
		fallthrough
	case 117:
		fallthrough
	case 118:
		fallthrough
	case 119:
		fallthrough
	case 120:
		fallthrough
	case 121:
		fallthrough
	case 122:
		fallthrough
	case 123:
		fallthrough
	case 124:
		fallthrough
	case 125:
		fallthrough
	case 126:
		fallthrough
	case 127:
		fallthrough
	case 128:
		fallthrough
	case 129:
		fallthrough
	case 130:
		fallthrough
	case 131:
		fallthrough
	case 132:
		fallthrough
	case 133:
		fallthrough
	case 134:
		fallthrough
	case 135:
		fallthrough
	case 136:
		fallthrough
	case 137:
		fallthrough
	case 138:
		fallthrough
	case 139:
		fallthrough
	case 140:
		fallthrough
	case 141:
		fallthrough
	case 142:
		fallthrough
	case 143:
		fallthrough
	case 144:
		fallthrough
	case 145:
		fallthrough
	case 146:
		fallthrough
	case 147:
		fallthrough
	case 148:
		fallthrough
	case 149:
		fallthrough
	case 150:
		fallthrough
	case 151:
		fallthrough
	case 152:
		fallthrough
	case 153:
		fallthrough
	case 154:
		fallthrough
	case 155:
		fallthrough
	case 156:
		fallthrough
	case 157:
		fallthrough
	case 158:
		fallthrough
	case 159:
		fallthrough
	case 160:
		fallthrough
	case 161:
		fallthrough
	case 162:
		fallthrough
	case 163:
		fallthrough
	case 164:
		fallthrough
	case 165:
		fallthrough
	case 166:
		fallthrough
	case 167:
		fallthrough
	case 168:
		fallthrough
	case 169:
		fallthrough
	case 170:
		fallthrough
	case 171:
		fallthrough
	case 172:
		fallthrough
	case 173:
		fallthrough
	case 174:
		fallthrough
	case 175:
		fallthrough
	case 176:
		fallthrough
	case 177:
		fallthrough
	case 178:
		fallthrough
	case 179:
		fallthrough
	case 180:
		fallthrough
	case 181:
		fallthrough
	case 182:
		fallthrough
	case 183:
		fallthrough
	case 184:
		fallthrough
	case 185:
		fallthrough
	case 186:
		fallthrough
	case 187:
		fallthrough
	case 188:
		fallthrough
	case 189:
		fallthrough
	case 190:
		fallthrough
	case 191:
		fallthrough
	case 192:
		fallthrough
	case 193:
		fallthrough
	case 194:
		fallthrough
	case 195:
		fallthrough
	case 196:
		fallthrough
	case 197:
		fallthrough
	case 198:
		fallthrough
	case 199:
		fallthrough
	case 200:
		fallthrough
	case 201:
		fallthrough
	case 202:
		fallthrough
	case 203:
		fallthrough
	case 204:
		fallthrough
	case 205:
		fallthrough
	case 206:
		fallthrough
	case 207:
		fallthrough
	case 208:
		fallthrough
	case 209:
		fallthrough
	case 210:
		fallthrough
	case 211:
		fallthrough
	case 212:
		fallthrough
	case 213:
		fallthrough
	case 214:
		fallthrough
	case 215:
		fallthrough
	case 216:
		fallthrough
	case 217:
		fallthrough
	case 218:
		fallthrough
	case 219:
		fallthrough
	case 220:
		fallthrough
	case 221:
		fallthrough
	case 222:
		fallthrough
	case 223:
		fallthrough
	case 224:
		fallthrough
	case 225:
		fallthrough
	case 226:
		fallthrough
	case 227:
		fallthrough
	case 228:
		fallthrough
	case 229:
		fallthrough
	case 230:
		fallthrough
	case 231:
		fallthrough
	case 232:
		fallthrough
	case 233:
		fallthrough
	case 234:
		fallthrough
	case 235:
		fallthrough
	case 236:
		fallthrough
	case 237:
		fallthrough
	case 238:
		fallthrough
	case 239:
		fallthrough
	case 240:
		fallthrough
	case 241:
		fallthrough
	case 242:
		fallthrough
	case 243:
		fallthrough
	case 244:
		fallthrough
	case 245:
		fallthrough
	case 246:
		fallthrough
	case 247:
		fallthrough
	case 248:
		fallthrough
	case 249:
		fallthrough
	case 250:
		fallthrough
	case 251:
		fallthrough
	case 252:
		fallthrough
	case 253:
		fallthrough
	case 254:
		fallthrough
	case 255:
		fallthrough
	case 256:
		*e = Protocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Protocol: %v", v)
	}
}
