// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReactivePolicyOutboundBodyDstEntityInfo struct {
	ID string `json:"id"`
}

func (o *ReactivePolicyOutboundBodyDstEntityInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReactivePolicyOutboundBodyExcludedSrcEntityInfo struct {
	ID string `json:"id"`
}

func (o *ReactivePolicyOutboundBodyExcludedSrcEntityInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReactivePolicyOutboundBodySrcEntityInfo struct {
	ID string `json:"id"`
}

func (o *ReactivePolicyOutboundBodySrcEntityInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReactivePolicyOutboundBodySrcUserInfo struct {
	ID string `json:"id"`
}

func (o *ReactivePolicyOutboundBodySrcUserInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReactivePolicyOutboundBody struct {
	AdditionalPortsList            []PortsList                                       `json:"additionalPortsList"`
	ChangeTicket                   *string                                           `json:"changeTicket,omitempty"`
	Description                    *string                                           `json:"description,omitempty"`
	DstEntityInfo                  ReactivePolicyOutboundBodyDstEntityInfo           `json:"dstEntityInfo"`
	DstPort                        string                                            `json:"dstPort"`
	DstProcessNames                []string                                          `json:"dstProcessNames,omitempty"`
	ExcludedSrcEntityInfos         []ReactivePolicyOutboundBodyExcludedSrcEntityInfo `json:"excludedSrcEntityInfos,omitempty"`
	ExcludedSrcProcesses           []string                                          `json:"excludedSrcProcesses,omitempty"`
	FallbackToLoggedOnUser         bool                                              `json:"fallbackToLoggedOnUser"`
	Name                           *string                                           `json:"name,omitempty"`
	MfaMethods                     []MfaMethods                                      `json:"mfaMethods"`
	OverrideBuiltins               bool                                              `json:"overrideBuiltins"`
	ProtocolType                   int64                                             `json:"protocolType"`
	RestrictToOriginatedUser       *bool                                             `json:"restrictToOriginatedUser,omitempty"`
	RestrictLoginToOriginatingUser *bool                                             `json:"restrictLoginToOriginatingUser,omitempty"`
	// * '1' - Hour
	// * '2' - Day
	// * '3' - Week
	// * '4' - Month
	// * '5' - Never
	// * '6' - 4 hours
	// * '7' - 12 hours
	// * '8' - 8 hours
	//
	RuleDuration    RuleDuration                              `json:"ruleDuration"`
	SrcEntityInfos  []ReactivePolicyOutboundBodySrcEntityInfo `json:"srcEntityInfos"`
	SrcProcessNames []string                                  `json:"srcProcessNames"`
	SrcUserInfos    []ReactivePolicyOutboundBodySrcUserInfo   `json:"srcUserInfos"`
	// * '1' - Enabled
	// * '2' - Disabled
	//
	State            ReactivePolicyState `json:"state"`
	UseDefaultIdp    *bool               `json:"useDefaultIdp,omitempty"`
	UseOccasionalMfa *bool               `json:"useOccasionalMfa,omitempty"`
}

func (o *ReactivePolicyOutboundBody) GetAdditionalPortsList() []PortsList {
	if o == nil {
		return []PortsList{}
	}
	return o.AdditionalPortsList
}

func (o *ReactivePolicyOutboundBody) GetChangeTicket() *string {
	if o == nil {
		return nil
	}
	return o.ChangeTicket
}

func (o *ReactivePolicyOutboundBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ReactivePolicyOutboundBody) GetDstEntityInfo() ReactivePolicyOutboundBodyDstEntityInfo {
	if o == nil {
		return ReactivePolicyOutboundBodyDstEntityInfo{}
	}
	return o.DstEntityInfo
}

func (o *ReactivePolicyOutboundBody) GetDstPort() string {
	if o == nil {
		return ""
	}
	return o.DstPort
}

func (o *ReactivePolicyOutboundBody) GetDstProcessNames() []string {
	if o == nil {
		return nil
	}
	return o.DstProcessNames
}

func (o *ReactivePolicyOutboundBody) GetExcludedSrcEntityInfos() []ReactivePolicyOutboundBodyExcludedSrcEntityInfo {
	if o == nil {
		return nil
	}
	return o.ExcludedSrcEntityInfos
}

func (o *ReactivePolicyOutboundBody) GetExcludedSrcProcesses() []string {
	if o == nil {
		return nil
	}
	return o.ExcludedSrcProcesses
}

func (o *ReactivePolicyOutboundBody) GetFallbackToLoggedOnUser() bool {
	if o == nil {
		return false
	}
	return o.FallbackToLoggedOnUser
}

func (o *ReactivePolicyOutboundBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ReactivePolicyOutboundBody) GetMfaMethods() []MfaMethods {
	if o == nil {
		return []MfaMethods{}
	}
	return o.MfaMethods
}

func (o *ReactivePolicyOutboundBody) GetOverrideBuiltins() bool {
	if o == nil {
		return false
	}
	return o.OverrideBuiltins
}

func (o *ReactivePolicyOutboundBody) GetProtocolType() int64 {
	if o == nil {
		return 0
	}
	return o.ProtocolType
}

func (o *ReactivePolicyOutboundBody) GetRestrictToOriginatedUser() *bool {
	if o == nil {
		return nil
	}
	return o.RestrictToOriginatedUser
}

func (o *ReactivePolicyOutboundBody) GetRestrictLoginToOriginatingUser() *bool {
	if o == nil {
		return nil
	}
	return o.RestrictLoginToOriginatingUser
}

func (o *ReactivePolicyOutboundBody) GetRuleDuration() RuleDuration {
	if o == nil {
		return RuleDuration(0)
	}
	return o.RuleDuration
}

func (o *ReactivePolicyOutboundBody) GetSrcEntityInfos() []ReactivePolicyOutboundBodySrcEntityInfo {
	if o == nil {
		return []ReactivePolicyOutboundBodySrcEntityInfo{}
	}
	return o.SrcEntityInfos
}

func (o *ReactivePolicyOutboundBody) GetSrcProcessNames() []string {
	if o == nil {
		return []string{}
	}
	return o.SrcProcessNames
}

func (o *ReactivePolicyOutboundBody) GetSrcUserInfos() []ReactivePolicyOutboundBodySrcUserInfo {
	if o == nil {
		return []ReactivePolicyOutboundBodySrcUserInfo{}
	}
	return o.SrcUserInfos
}

func (o *ReactivePolicyOutboundBody) GetState() ReactivePolicyState {
	if o == nil {
		return ReactivePolicyState(0)
	}
	return o.State
}

func (o *ReactivePolicyOutboundBody) GetUseDefaultIdp() *bool {
	if o == nil {
		return nil
	}
	return o.UseDefaultIdp
}

func (o *ReactivePolicyOutboundBody) GetUseOccasionalMfa() *bool {
	if o == nil {
		return nil
	}
	return o.UseOccasionalMfa
}
