// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReactivePolicyItem struct {
	Item *ReactivePolicy `json:"item,omitempty"`
}

func (r *ReactivePolicyItem) GetItem() *ReactivePolicy {
	if r == nil {
		return nil
	}
	return r.Item
}
