// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReactivePolicyInboundBodyDstEntityInfo struct {
	ID string `json:"id"`
}

func (r *ReactivePolicyInboundBodyDstEntityInfo) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type ReactivePolicyInboundBodyExcludedSrcEntityInfo struct {
	ID string `json:"id"`
}

func (r *ReactivePolicyInboundBodyExcludedSrcEntityInfo) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type ReactivePolicyInboundBodySrcEntityInfo struct {
	ID string `json:"id"`
}

func (r *ReactivePolicyInboundBodySrcEntityInfo) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type ReactivePolicyInboundBodySrcUserInfo struct {
	ID string `json:"id"`
}

func (r *ReactivePolicyInboundBodySrcUserInfo) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type ReactivePolicyInboundBody struct {
	AdditionalPortsList            []PortsList                                      `json:"additionalPortsList"`
	ChangeTicket                   *string                                          `json:"changeTicket,omitempty"`
	Description                    *string                                          `json:"description,omitempty"`
	DstEntityInfo                  ReactivePolicyInboundBodyDstEntityInfo           `json:"dstEntityInfo"`
	DstPort                        string                                           `json:"dstPort"`
	DstProcessNames                []string                                         `json:"dstProcessNames"`
	ExcludedSrcEntityInfos         []ReactivePolicyInboundBodyExcludedSrcEntityInfo `json:"excludedSrcEntityInfos,omitempty"`
	ExcludedSrcProcesses           []string                                         `json:"excludedSrcProcesses,omitempty"`
	FallbackToLoggedOnUser         bool                                             `json:"fallbackToLoggedOnUser"`
	IdentityProtectionCategoryList []IdentityProtectionCategory                     `json:"identityProtectionCategoryList,omitempty"`
	Name                           *string                                          `json:"name,omitempty"`
	MfaMethods                     []MfaMethods                                     `json:"mfaMethods"`
	OverrideBuiltins               bool                                             `json:"overrideBuiltins"`
	ProtocolType                   int64                                            `json:"protocolType"`
	RestrictLoginToOriginatingUser *bool                                            `json:"restrictLoginToOriginatingUser,omitempty"`
	// * '1' - Hour
	// * '2' - Day
	// * '3' - Week
	// * '4' - Month
	// * '5' - Never
	// * '6' - 4 hours
	// * '7' - 12 hours
	// * '8' - 8 hours
	//
	RuleDuration    RuleDuration                             `json:"ruleDuration"`
	SrcEntityInfos  []ReactivePolicyInboundBodySrcEntityInfo `json:"srcEntityInfos"`
	SrcProcessNames []string                                 `json:"srcProcessNames"`
	SrcUserInfos    []ReactivePolicyInboundBodySrcUserInfo   `json:"srcUserInfos"`
	// * '1' - Enabled
	// * '2' - Disabled
	//
	State            ReactivePolicyState `json:"state"`
	UseDefaultIdp    *bool               `json:"useDefaultIdp,omitempty"`
	UseOccasionalMfa *bool               `json:"useOccasionalMfa,omitempty"`
}

func (r *ReactivePolicyInboundBody) GetAdditionalPortsList() []PortsList {
	if r == nil {
		return []PortsList{}
	}
	return r.AdditionalPortsList
}

func (r *ReactivePolicyInboundBody) GetChangeTicket() *string {
	if r == nil {
		return nil
	}
	return r.ChangeTicket
}

func (r *ReactivePolicyInboundBody) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReactivePolicyInboundBody) GetDstEntityInfo() ReactivePolicyInboundBodyDstEntityInfo {
	if r == nil {
		return ReactivePolicyInboundBodyDstEntityInfo{}
	}
	return r.DstEntityInfo
}

func (r *ReactivePolicyInboundBody) GetDstPort() string {
	if r == nil {
		return ""
	}
	return r.DstPort
}

func (r *ReactivePolicyInboundBody) GetDstProcessNames() []string {
	if r == nil {
		return []string{}
	}
	return r.DstProcessNames
}

func (r *ReactivePolicyInboundBody) GetExcludedSrcEntityInfos() []ReactivePolicyInboundBodyExcludedSrcEntityInfo {
	if r == nil {
		return nil
	}
	return r.ExcludedSrcEntityInfos
}

func (r *ReactivePolicyInboundBody) GetExcludedSrcProcesses() []string {
	if r == nil {
		return nil
	}
	return r.ExcludedSrcProcesses
}

func (r *ReactivePolicyInboundBody) GetFallbackToLoggedOnUser() bool {
	if r == nil {
		return false
	}
	return r.FallbackToLoggedOnUser
}

func (r *ReactivePolicyInboundBody) GetIdentityProtectionCategoryList() []IdentityProtectionCategory {
	if r == nil {
		return nil
	}
	return r.IdentityProtectionCategoryList
}

func (r *ReactivePolicyInboundBody) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *ReactivePolicyInboundBody) GetMfaMethods() []MfaMethods {
	if r == nil {
		return []MfaMethods{}
	}
	return r.MfaMethods
}

func (r *ReactivePolicyInboundBody) GetOverrideBuiltins() bool {
	if r == nil {
		return false
	}
	return r.OverrideBuiltins
}

func (r *ReactivePolicyInboundBody) GetProtocolType() int64 {
	if r == nil {
		return 0
	}
	return r.ProtocolType
}

func (r *ReactivePolicyInboundBody) GetRestrictLoginToOriginatingUser() *bool {
	if r == nil {
		return nil
	}
	return r.RestrictLoginToOriginatingUser
}

func (r *ReactivePolicyInboundBody) GetRuleDuration() RuleDuration {
	if r == nil {
		return RuleDuration(0)
	}
	return r.RuleDuration
}

func (r *ReactivePolicyInboundBody) GetSrcEntityInfos() []ReactivePolicyInboundBodySrcEntityInfo {
	if r == nil {
		return []ReactivePolicyInboundBodySrcEntityInfo{}
	}
	return r.SrcEntityInfos
}

func (r *ReactivePolicyInboundBody) GetSrcProcessNames() []string {
	if r == nil {
		return []string{}
	}
	return r.SrcProcessNames
}

func (r *ReactivePolicyInboundBody) GetSrcUserInfos() []ReactivePolicyInboundBodySrcUserInfo {
	if r == nil {
		return []ReactivePolicyInboundBodySrcUserInfo{}
	}
	return r.SrcUserInfos
}

func (r *ReactivePolicyInboundBody) GetState() ReactivePolicyState {
	if r == nil {
		return ReactivePolicyState(0)
	}
	return r.State
}

func (r *ReactivePolicyInboundBody) GetUseDefaultIdp() *bool {
	if r == nil {
		return nil
	}
	return r.UseDefaultIdp
}

func (r *ReactivePolicyInboundBody) GetUseOccasionalMfa() *bool {
	if r == nil {
		return nil
	}
	return r.UseOccasionalMfa
}
