// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReactivePolicyItem struct {
	Item *ReactivePolicy `json:"item,omitempty"`
}

func (o *ReactivePolicyItem) GetItem() *ReactivePolicy {
	if o == nil {
		return nil
	}
	return o.Item
}
