// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RPCProtocolsList int

const (
	RPCProtocolsListOne RPCProtocolsList = 1
	RPCProtocolsListTwo RPCProtocolsList = 2
)

func (e RPCProtocolsList) ToPointer() *RPCProtocolsList {
	return &e
}
func (e *RPCProtocolsList) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		*e = RPCProtocolsList(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RPCProtocolsList: %v", v)
	}
}
