// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RPCRuleBody struct {
	// * 1 - Allow
	// * 2 - Block
	//
	Action               RuleAction `json:"action"`
	ChangeTicket         *string    `json:"changeTicket,omitempty"`
	Description          string     `json:"description"`
	ExcludedAssetIdsList []string   `json:"excludedAssetIdsList"`
	// Epoch Millis
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
	// one of the following:
	// * "rpcAnyInterface" for any interface
	// * List of interface uuids for explicit interfaces
	//
	InterfaceUuidsList []string `json:"interfaceUuidsList"`
	LocalAssetID       string   `json:"localAssetId"`
	Name               *string  `json:"name,omitempty"`
	OpNumbersList      []int64  `json:"opNumbersList"`
	// * NULL - Any
	// * '1' - Rules RPC over SMB
	// * '2' - Rules RPC over TCP
	//
	ProtocolsList      []*RPCProtocolsList `json:"protocolsList"`
	RemoteAssetIdsList []string            `json:"remoteAssetIdsList"`
	// * '1' - Enabled
	// * '2' - Disabled
	//
	State       RuleStateBody `json:"state"`
	UserIdsList []string      `json:"userIdsList"`
}

func (o *RPCRuleBody) GetAction() RuleAction {
	if o == nil {
		return RuleAction(0)
	}
	return o.Action
}

func (o *RPCRuleBody) GetChangeTicket() *string {
	if o == nil {
		return nil
	}
	return o.ChangeTicket
}

func (o *RPCRuleBody) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *RPCRuleBody) GetExcludedAssetIdsList() []string {
	if o == nil {
		return []string{}
	}
	return o.ExcludedAssetIdsList
}

func (o *RPCRuleBody) GetExpiresAt() *int64 {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *RPCRuleBody) GetInterfaceUuidsList() []string {
	if o == nil {
		return []string{}
	}
	return o.InterfaceUuidsList
}

func (o *RPCRuleBody) GetLocalAssetID() string {
	if o == nil {
		return ""
	}
	return o.LocalAssetID
}

func (o *RPCRuleBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *RPCRuleBody) GetOpNumbersList() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.OpNumbersList
}

func (o *RPCRuleBody) GetProtocolsList() []*RPCProtocolsList {
	if o == nil {
		return []*RPCProtocolsList{}
	}
	return o.ProtocolsList
}

func (o *RPCRuleBody) GetRemoteAssetIdsList() []string {
	if o == nil {
		return []string{}
	}
	return o.RemoteAssetIdsList
}

func (o *RPCRuleBody) GetState() RuleStateBody {
	if o == nil {
		return RuleStateBody(0)
	}
	return o.State
}

func (o *RPCRuleBody) GetUserIdsList() []string {
	if o == nil {
		return []string{}
	}
	return o.UserIdsList
}
