// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RPCRuleBody struct {
	// * 1 - Allow
	// * 2 - Block
	//
	Action               RuleAction `json:"action"`
	ChangeTicket         *string    `json:"changeTicket,omitempty"`
	Description          string     `json:"description"`
	ExcludedAssetIdsList []string   `json:"excludedAssetIdsList"`
	// Epoch Millis
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
	// one of the following:
	// * "rpcAnyInterface" for any interface
	// * List of interface uuids for explicit interfaces
	//
	InterfaceUuidsList []string `json:"interfaceUuidsList"`
	LocalAssetID       string   `json:"localAssetId"`
	Name               *string  `json:"name,omitempty"`
	OpNumbersList      []int64  `json:"opNumbersList"`
	// * NULL - Any
	// * '1' - Rules RPC over SMB
	// * '2' - Rules RPC over TCP
	//
	ProtocolsList      []int64  `json:"protocolsList"`
	RemoteAssetIdsList []string `json:"remoteAssetIdsList"`
	// * '1' - Enabled
	// * '2' - Disabled
	// * '3' - Deleted By User
	// * '4' - Pending Review
	// * '5' - Pending Review Auto
	// * '6' - Rejected by User
	// * '7' - Excluded by User
	//
	State       RuleState `json:"state"`
	UserIdsList []string  `json:"userIdsList"`
}

func (r *RPCRuleBody) GetAction() RuleAction {
	if r == nil {
		return RuleAction(0)
	}
	return r.Action
}

func (r *RPCRuleBody) GetChangeTicket() *string {
	if r == nil {
		return nil
	}
	return r.ChangeTicket
}

func (r *RPCRuleBody) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RPCRuleBody) GetExcludedAssetIdsList() []string {
	if r == nil {
		return []string{}
	}
	return r.ExcludedAssetIdsList
}

func (r *RPCRuleBody) GetExpiresAt() *int64 {
	if r == nil {
		return nil
	}
	return r.ExpiresAt
}

func (r *RPCRuleBody) GetInterfaceUuidsList() []string {
	if r == nil {
		return []string{}
	}
	return r.InterfaceUuidsList
}

func (r *RPCRuleBody) GetLocalAssetID() string {
	if r == nil {
		return ""
	}
	return r.LocalAssetID
}

func (r *RPCRuleBody) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RPCRuleBody) GetOpNumbersList() []int64 {
	if r == nil {
		return []int64{}
	}
	return r.OpNumbersList
}

func (r *RPCRuleBody) GetProtocolsList() []int64 {
	if r == nil {
		return []int64{}
	}
	return r.ProtocolsList
}

func (r *RPCRuleBody) GetRemoteAssetIdsList() []string {
	if r == nil {
		return []string{}
	}
	return r.RemoteAssetIdsList
}

func (r *RPCRuleBody) GetState() RuleState {
	if r == nil {
		return RuleState(0)
	}
	return r.State
}

func (r *RPCRuleBody) GetUserIdsList() []string {
	if r == nil {
		return []string{}
	}
	return r.UserIdsList
}
