// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RPCRule struct {
	// * 1 - Allow
	// * 2 - Block
	//
	Action       *RuleAction `json:"action,omitempty"`
	ChangeTicket *string     `json:"changeTicket,omitempty"`
	// Epoch Millis
	CreatedAt            *int64       `json:"createdAt,omitempty"`
	CreatedBy            *CreatedBy   `json:"createdBy,omitempty"`
	Description          *string      `json:"description,omitempty"`
	ExcludedAssetIdsList []string     `json:"excludedAssetIdsList,omitempty"`
	ExcludedAssetInfos   []IDNamePair `json:"excludedAssetInfos,omitempty"`
	// Epoch Millis
	ExpiresAt *int64  `json:"expiresAt,omitempty"`
	ID        *string `json:"id,omitempty"`
	// one of the following:
	// * "rpcAnyInterface" for any interface
	// * List of interface uuids for explicit interfaces
	//
	InterfaceUuidsList []string    `json:"interfaceUuidsList,omitempty"`
	LocalAssetID       *string     `json:"localAssetId,omitempty"`
	LocalAssetInfo     *IDNamePair `json:"localAssetInfo,omitempty"`
	Name               *string     `json:"name,omitempty"`
	OpNumbersList      []int64     `json:"opNumbersList,omitempty"`
	ParentID           *string     `json:"parentId,omitempty"`
	ParentType         *int        `json:"parentType,omitempty"`
	// * NULL - Any
	// * '1' - Rules RPC over SMB
	// * '2' - Rules RPC over TCP
	//
	ProtocolsList      []int64      `json:"protocolsList,omitempty"`
	RemoteAssetIdsList []string     `json:"remoteAssetIdsList,omitempty"`
	RemoteAssetInfos   []IDNamePair `json:"remoteAssetInfos,omitempty"`
	// * '1' - Trivial
	// * '2' - Permissive
	// * '3' - Privileged
	// * '4' - Critical
	// * '5' - System
	// * '6' - Preventative
	// * '8' - Dangerous
	//
	RuleClass *RuleClass `json:"ruleClass,omitempty"`
	// * '1' - Enabled
	// * '2' - Disabled
	// * '3' - Deleted By User
	// * '4' - Pending Review
	// * '5' - Pending Review Auto
	// * '6' - Rejected by User
	// * '7' - Excluded by User
	//
	State *RuleState `json:"state,omitempty"`
	// Epoch Millis
	UpdatedAt   *int64       `json:"updatedAt,omitempty"`
	UpdatedBy   *IDNamePair  `json:"updatedBy,omitempty"`
	UserIdsList []string     `json:"userIdsList,omitempty"`
	UserInfos   []IDNamePair `json:"userInfos,omitempty"`
}

func (r *RPCRule) GetAction() *RuleAction {
	if r == nil {
		return nil
	}
	return r.Action
}

func (r *RPCRule) GetChangeTicket() *string {
	if r == nil {
		return nil
	}
	return r.ChangeTicket
}

func (r *RPCRule) GetCreatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RPCRule) GetCreatedBy() *CreatedBy {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *RPCRule) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RPCRule) GetExcludedAssetIdsList() []string {
	if r == nil {
		return nil
	}
	return r.ExcludedAssetIdsList
}

func (r *RPCRule) GetExcludedAssetInfos() []IDNamePair {
	if r == nil {
		return nil
	}
	return r.ExcludedAssetInfos
}

func (r *RPCRule) GetExpiresAt() *int64 {
	if r == nil {
		return nil
	}
	return r.ExpiresAt
}

func (r *RPCRule) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RPCRule) GetInterfaceUuidsList() []string {
	if r == nil {
		return nil
	}
	return r.InterfaceUuidsList
}

func (r *RPCRule) GetLocalAssetID() *string {
	if r == nil {
		return nil
	}
	return r.LocalAssetID
}

func (r *RPCRule) GetLocalAssetInfo() *IDNamePair {
	if r == nil {
		return nil
	}
	return r.LocalAssetInfo
}

func (r *RPCRule) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RPCRule) GetOpNumbersList() []int64 {
	if r == nil {
		return nil
	}
	return r.OpNumbersList
}

func (r *RPCRule) GetParentID() *string {
	if r == nil {
		return nil
	}
	return r.ParentID
}

func (r *RPCRule) GetParentType() *int {
	if r == nil {
		return nil
	}
	return r.ParentType
}

func (r *RPCRule) GetProtocolsList() []int64 {
	if r == nil {
		return nil
	}
	return r.ProtocolsList
}

func (r *RPCRule) GetRemoteAssetIdsList() []string {
	if r == nil {
		return nil
	}
	return r.RemoteAssetIdsList
}

func (r *RPCRule) GetRemoteAssetInfos() []IDNamePair {
	if r == nil {
		return nil
	}
	return r.RemoteAssetInfos
}

func (r *RPCRule) GetRuleClass() *RuleClass {
	if r == nil {
		return nil
	}
	return r.RuleClass
}

func (r *RPCRule) GetState() *RuleState {
	if r == nil {
		return nil
	}
	return r.State
}

func (r *RPCRule) GetUpdatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *RPCRule) GetUpdatedBy() *IDNamePair {
	if r == nil {
		return nil
	}
	return r.UpdatedBy
}

func (r *RPCRule) GetUserIdsList() []string {
	if r == nil {
		return nil
	}
	return r.UserIdsList
}

func (r *RPCRule) GetUserInfos() []IDNamePair {
	if r == nil {
		return nil
	}
	return r.UserInfos
}
