// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RuleReviewReason - Mandatory object for rule review approve_with_changes / reject.
//
//	reason: {
//	    HUMAN_TRAFFIC_COVERED_BY_MFA = 1,
//	    TIGHTEN_RULE_SCOPE = 2,
//	    MISSING_PORT_OR_PROCESS = 3,
//	    AFFECTED_ENTITIES_CONTAINED_IN_AN_EXISTING_GROUP = 4,
//	    REDUNDANT_RULE = 5,
//	    TRAFFIC_SHOULD_BE_BLOCKED = 6,
//	    OTHER = 7
//	}
type RuleReviewReason struct {
	Reason int64 `json:"reason"`
	// Optional if reason != OTHER(7), mandatory if reason == OTHER(7)
	Details *string `json:"details,omitempty"`
}

func (r *RuleReviewReason) GetReason() int64 {
	if r == nil {
		return 0
	}
	return r.Reason
}

func (r *RuleReviewReason) GetDetails() *string {
	if r == nil {
		return nil
	}
	return r.Details
}
