// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RuleResponse struct {
	Item *Rule `json:"item,omitempty"`
}

func (r *RuleResponse) GetItem() *Rule {
	if r == nil {
		return nil
	}
	return r.Item
}
