// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RuleStateBody - * '1' - Enabled
// * '2' - Disabled
type RuleStateBody int

const (
	RuleStateBodyOne RuleStateBody = 1
	RuleStateBodyTwo RuleStateBody = 2
)

func (e RuleStateBody) ToPointer() *RuleStateBody {
	return &e
}
func (e *RuleStateBody) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		*e = RuleStateBody(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RuleStateBody: %v", v)
	}
}
