// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RuleBody struct {
	// * 1 - Allow
	// * 2 - Block
	//
	Action               RuleAction `json:"action"`
	ChangeTicket         *string    `json:"changeTicket,omitempty"`
	Description          *string    `json:"description,omitempty"`
	ExcludedLocalIdsList []string   `json:"excludedLocalIdsList,omitempty"`
	// Epoch Millis
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
	// * For allow rule only.
	// * '1' - Off
	// * '2' - Null encapsulation connections
	// * '3' - Authenticated and integrity-protected connections
	// * '4' - Encrypted connections and dynamically negotiate encryption (inbound rule only)
	// * '5' - Encrypted connections
	//
	IPSecOpt            *IPSecOpt      `json:"ipSecOpt,omitempty"`
	Name                *string        `json:"name,omitempty"`
	LocalEntityID       string         `json:"localEntityId"`
	LocalProcessesList  []string       `json:"localProcessesList"`
	ServicesList        []string       `json:"servicesList,omitempty"`
	PortsList           []PortsList    `json:"portsList"`
	RemoteEntityIdsList []string       `json:"remoteEntityIdsList"`
	SrcUsersList        []SrcUsersList `json:"srcUsersList,omitempty"`
	// * '1' - Enabled
	// * '2' - Disabled
	// * '3' - Deleted By User
	// * '4' - Pending Review
	// * '5' - Pending Review Auto
	// * '6' - Rejected by User
	// * '7' - Excluded by User
	//
	State   RuleState `json:"state"`
	Context *int      `json:"context,omitempty"`
}

func (r *RuleBody) GetAction() RuleAction {
	if r == nil {
		return RuleAction(0)
	}
	return r.Action
}

func (r *RuleBody) GetChangeTicket() *string {
	if r == nil {
		return nil
	}
	return r.ChangeTicket
}

func (r *RuleBody) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RuleBody) GetExcludedLocalIdsList() []string {
	if r == nil {
		return nil
	}
	return r.ExcludedLocalIdsList
}

func (r *RuleBody) GetExpiresAt() *int64 {
	if r == nil {
		return nil
	}
	return r.ExpiresAt
}

func (r *RuleBody) GetIPSecOpt() *IPSecOpt {
	if r == nil {
		return nil
	}
	return r.IPSecOpt
}

func (r *RuleBody) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RuleBody) GetLocalEntityID() string {
	if r == nil {
		return ""
	}
	return r.LocalEntityID
}

func (r *RuleBody) GetLocalProcessesList() []string {
	if r == nil {
		return []string{}
	}
	return r.LocalProcessesList
}

func (r *RuleBody) GetServicesList() []string {
	if r == nil {
		return nil
	}
	return r.ServicesList
}

func (r *RuleBody) GetPortsList() []PortsList {
	if r == nil {
		return []PortsList{}
	}
	return r.PortsList
}

func (r *RuleBody) GetRemoteEntityIdsList() []string {
	if r == nil {
		return []string{}
	}
	return r.RemoteEntityIdsList
}

func (r *RuleBody) GetSrcUsersList() []SrcUsersList {
	if r == nil {
		return nil
	}
	return r.SrcUsersList
}

func (r *RuleBody) GetState() RuleState {
	if r == nil {
		return RuleState(0)
	}
	return r.State
}

func (r *RuleBody) GetContext() *int {
	if r == nil {
		return nil
	}
	return r.Context
}
