// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SrcUsersList struct {
	ID  *string `json:"id,omitempty"`
	Sid *string `json:"sid,omitempty"`
}

func (o *SrcUsersList) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SrcUsersList) GetSid() *string {
	if o == nil {
		return nil
	}
	return o.Sid
}
