// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/operations"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
)

func (r *AssetIDDataSourceModel) RefreshFromSharedAssetIDSearch(ctx context.Context, resp *shared.AssetIDSearch) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AssetID = types.StringPointerValue(resp.AssetID)
	}

	return diags
}

func (r *AssetIDDataSourceModel) ToOperationsAssetsSearchRequest(ctx context.Context) (*operations.AssetsSearchRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	fqdn := new(string)
	if !r.Fqdn.IsUnknown() && !r.Fqdn.IsNull() {
		*fqdn = r.Fqdn.ValueString()
	} else {
		fqdn = nil
	}
	out := operations.AssetsSearchRequest{
		Fqdn: fqdn,
	}

	return &out, diags
}
