// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/operations"
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
)

func (r *CustomGroupMembersResourceModel) RefreshFromSharedGroupMembersList(ctx context.Context, resp *shared.GroupMembersList) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.MembersID = make([]types.String, 0, len(resp.MembersID))
		for _, v := range resp.MembersID {
			r.MembersID = append(r.MembersID, types.StringValue(v))
		}
	}

	return diags
}

func (r *CustomGroupMembersResourceModel) ToOperationsCustomGroupMembersListRequest(ctx context.Context) (*operations.CustomGroupMembersListRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.CustomGroupMembersListRequest{
		ID: id,
	}

	return &out, diags
}

func (r *CustomGroupMembersResourceModel) ToOperationsCustomGroupsMembersAddRequest(ctx context.Context) (*operations.CustomGroupsMembersAddRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	customGroupMembersBody, customGroupMembersBodyDiags := r.ToSharedCustomGroupMembersBody(ctx)
	diags.Append(customGroupMembersBodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CustomGroupsMembersAddRequest{
		ID:                     id,
		CustomGroupMembersBody: *customGroupMembersBody,
	}

	return &out, diags
}

func (r *CustomGroupMembersResourceModel) ToOperationsCustomGroupsMembersDeleteRequest(ctx context.Context) (*operations.CustomGroupsMembersDeleteRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	customGroupMembersBody, customGroupMembersBodyDiags := r.ToSharedCustomGroupMembersBody(ctx)
	diags.Append(customGroupMembersBodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CustomGroupsMembersDeleteRequest{
		ID:                     id,
		CustomGroupMembersBody: *customGroupMembersBody,
	}

	return &out, diags
}

func (r *CustomGroupMembersResourceModel) ToSharedCustomGroupMembersBody(ctx context.Context) (*shared.CustomGroupMembersBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	membersID := make([]string, 0, len(r.MembersID))
	for membersIDIndex := range r.MembersID {
		membersID = append(membersID, r.MembersID[membersIDIndex].ValueString())
	}
	out := shared.CustomGroupMembersBody{
		MembersID: membersID,
	}

	return &out, diags
}
