// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/speakeasy/terraform-provider-zeronetworks/internal/provider/types"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/operations"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
)

func (r *InboundMFAPolicyDataSourceModel) ToOperationsMFAInboundPoliciesGetRequest(ctx context.Context) (*operations.MFAInboundPoliciesGetRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.MFAInboundPoliciesGetRequest{
		ID: id,
	}

	return &out, diags
}

func (r *InboundMFAPolicyDataSourceModel) RefreshFromSharedReactivePolicy(ctx context.Context, resp *shared.ReactivePolicy) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AdditionalPortsList = []tfTypes.PortsList{}
		if len(r.AdditionalPortsList) > len(resp.AdditionalPortsList) {
			r.AdditionalPortsList = r.AdditionalPortsList[:len(resp.AdditionalPortsList)]
		}
		for additionalPortsListCount, additionalPortsListItem := range resp.AdditionalPortsList {
			var additionalPortsList tfTypes.PortsList
			additionalPortsList.Ports = types.StringPointerValue(additionalPortsListItem.Ports)
			if additionalPortsListItem.ProtocolType != nil {
				additionalPortsList.ProtocolType = types.Int32Value(int32(*additionalPortsListItem.ProtocolType))
			} else {
				additionalPortsList.ProtocolType = types.Int32Null()
			}
			if additionalPortsListCount+1 > len(r.AdditionalPortsList) {
				r.AdditionalPortsList = append(r.AdditionalPortsList, additionalPortsList)
			} else {
				r.AdditionalPortsList[additionalPortsListCount].Ports = additionalPortsList.Ports
				r.AdditionalPortsList[additionalPortsListCount].ProtocolType = additionalPortsList.ProtocolType
			}
		}
		r.ChangeTicket = types.StringPointerValue(resp.ChangeTicket)
		r.Context = types.Int64PointerValue(resp.Context)
		r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.CreatedByName = types.StringPointerValue(resp.CreatedByName)
		r.Description = types.StringPointerValue(resp.Description)
		if resp.DstEntityInfo == nil {
			r.DstEntityInfo = nil
		} else {
			r.DstEntityInfo = &tfTypes.IDNamePair1{}
			r.DstEntityInfo.ID = types.StringPointerValue(resp.DstEntityInfo.ID)
			r.DstEntityInfo.Name = types.StringPointerValue(resp.DstEntityInfo.Name)
		}
		r.DstPort = types.StringPointerValue(resp.DstPort)
		r.DstProcessNames = make([]types.String, 0, len(resp.DstProcessNames))
		for _, v := range resp.DstProcessNames {
			r.DstProcessNames = append(r.DstProcessNames, types.StringValue(v))
		}
		if resp.EnforcementSource != nil {
			r.EnforcementSource = types.Int32Value(int32(*resp.EnforcementSource))
		} else {
			r.EnforcementSource = types.Int32Null()
		}
		r.ExcludedSrcEntityInfos = []tfTypes.IDNamePair1{}
		if len(r.ExcludedSrcEntityInfos) > len(resp.ExcludedSrcEntityInfos) {
			r.ExcludedSrcEntityInfos = r.ExcludedSrcEntityInfos[:len(resp.ExcludedSrcEntityInfos)]
		}
		for excludedSrcEntityInfosCount, excludedSrcEntityInfosItem := range resp.ExcludedSrcEntityInfos {
			var excludedSrcEntityInfos tfTypes.IDNamePair1
			excludedSrcEntityInfos.ID = types.StringPointerValue(excludedSrcEntityInfosItem.ID)
			excludedSrcEntityInfos.Name = types.StringPointerValue(excludedSrcEntityInfosItem.Name)
			if excludedSrcEntityInfosCount+1 > len(r.ExcludedSrcEntityInfos) {
				r.ExcludedSrcEntityInfos = append(r.ExcludedSrcEntityInfos, excludedSrcEntityInfos)
			} else {
				r.ExcludedSrcEntityInfos[excludedSrcEntityInfosCount].ID = excludedSrcEntityInfos.ID
				r.ExcludedSrcEntityInfos[excludedSrcEntityInfosCount].Name = excludedSrcEntityInfos.Name
			}
		}
		r.ExcludedSrcProcesses = make([]types.String, 0, len(resp.ExcludedSrcProcesses))
		for _, v := range resp.ExcludedSrcProcesses {
			r.ExcludedSrcProcesses = append(r.ExcludedSrcProcesses, types.StringValue(v))
		}
		r.FallbackToLoggedOnUser = types.BoolPointerValue(resp.FallbackToLoggedOnUser)
		r.ID = types.StringPointerValue(resp.ID)
		r.IdentityProtectionCategoryList = make([]types.Int32, 0, len(resp.IdentityProtectionCategoryList))
		for _, v := range resp.IdentityProtectionCategoryList {
			r.IdentityProtectionCategoryList = append(r.IdentityProtectionCategoryList, types.Int32Value(int32(int(v))))
		}
		r.MfaMethods = make([]types.Int32, 0, len(resp.MfaMethods))
		for _, v := range resp.MfaMethods {
			r.MfaMethods = append(r.MfaMethods, types.Int32Value(int32(int(v))))
		}
		r.Name = types.StringPointerValue(resp.Name)
		r.OverrideBuiltins = types.BoolPointerValue(resp.OverrideBuiltins)
		if resp.ProtocolType != nil {
			r.ProtocolType = types.Int32Value(int32(*resp.ProtocolType))
		} else {
			r.ProtocolType = types.Int32Null()
		}
		r.RestrictLoginToOriginatingUser = types.BoolPointerValue(resp.RestrictLoginToOriginatingUser)
		r.RestrictToOriginatedUser = types.BoolPointerValue(resp.RestrictToOriginatedUser)
		if resp.RuleDuration != nil {
			r.RuleDuration = types.Int32Value(int32(*resp.RuleDuration))
		} else {
			r.RuleDuration = types.Int32Null()
		}
		r.SrcEntityInfos = []tfTypes.IDNamePair1{}
		if len(r.SrcEntityInfos) > len(resp.SrcEntityInfos) {
			r.SrcEntityInfos = r.SrcEntityInfos[:len(resp.SrcEntityInfos)]
		}
		for srcEntityInfosCount, srcEntityInfosItem := range resp.SrcEntityInfos {
			var srcEntityInfos tfTypes.IDNamePair1
			srcEntityInfos.ID = types.StringPointerValue(srcEntityInfosItem.ID)
			srcEntityInfos.Name = types.StringPointerValue(srcEntityInfosItem.Name)
			if srcEntityInfosCount+1 > len(r.SrcEntityInfos) {
				r.SrcEntityInfos = append(r.SrcEntityInfos, srcEntityInfos)
			} else {
				r.SrcEntityInfos[srcEntityInfosCount].ID = srcEntityInfos.ID
				r.SrcEntityInfos[srcEntityInfosCount].Name = srcEntityInfos.Name
			}
		}
		r.SrcProcessNames = make([]types.String, 0, len(resp.SrcProcessNames))
		for _, v := range resp.SrcProcessNames {
			r.SrcProcessNames = append(r.SrcProcessNames, types.StringValue(v))
		}
		r.SrcUserInfos = []tfTypes.IDNamePair1{}
		if len(r.SrcUserInfos) > len(resp.SrcUserInfos) {
			r.SrcUserInfos = r.SrcUserInfos[:len(resp.SrcUserInfos)]
		}
		for srcUserInfosCount, srcUserInfosItem := range resp.SrcUserInfos {
			var srcUserInfos tfTypes.IDNamePair1
			srcUserInfos.ID = types.StringPointerValue(srcUserInfosItem.ID)
			srcUserInfos.Name = types.StringPointerValue(srcUserInfosItem.Name)
			if srcUserInfosCount+1 > len(r.SrcUserInfos) {
				r.SrcUserInfos = append(r.SrcUserInfos, srcUserInfos)
			} else {
				r.SrcUserInfos[srcUserInfosCount].ID = srcUserInfos.ID
				r.SrcUserInfos[srcUserInfosCount].Name = srcUserInfos.Name
			}
		}
		if resp.State != nil {
			r.State = types.Int32Value(int32(*resp.State))
		} else {
			r.State = types.Int32Null()
		}
		r.UpdatedAt = types.Int64PointerValue(resp.UpdatedAt)
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
		r.UpdatedByName = types.StringPointerValue(resp.UpdatedByName)
		r.UseDefaultIdp = types.BoolPointerValue(resp.UseDefaultIdp)
		r.UseOccasionalMfa = types.BoolPointerValue(resp.UseOccasionalMfa)
	}

	return diags
}
