// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/provider/typeconvert"
	tfTypes "github.com/speakeasy/terraform-provider-zeronetworks/internal/provider/types"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/operations"
	"github.com/speakeasy/terraform-provider-zeronetworks/internal/sdk/models/shared"
)

func (r *InboundRuleDataSourceModel) ToOperationsInboundRuleGetRequest(ctx context.Context) (*operations.InboundRuleGetRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.InboundRuleGetRequest{
		ID: id,
	}

	return &out, diags
}

func (r *InboundRuleDataSourceModel) RefreshFromSharedRule(ctx context.Context, resp *shared.Rule) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Action != nil {
			r.Action = types.Int32Value(int32(*resp.Action))
		} else {
			r.Action = types.Int32Null()
		}
		r.ActivitiesCount = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.ActivitiesCount))
		r.AeOverridden = types.BoolPointerValue(resp.AeOverridden)
		r.ApprovedAt = types.Int64PointerValue(resp.ApprovedAt)
		if resp.ApprovedBy == nil {
			r.ApprovedBy = nil
		} else {
			r.ApprovedBy = &tfTypes.IDNamePair1{}
			r.ApprovedBy.ID = types.StringPointerValue(resp.ApprovedBy.ID)
			r.ApprovedBy.Name = types.StringPointerValue(resp.ApprovedBy.Name)
		}
		r.ChangeTicket = types.StringPointerValue(resp.ChangeTicket)
		r.Context = types.Int64PointerValue(resp.Context)
		r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
		if resp.CreatedBy == nil {
			r.CreatedBy = nil
		} else {
			r.CreatedBy = &tfTypes.CreatedBy{}
			if resp.CreatedBy.CreatedBy == nil {
				r.CreatedBy.CreatedBy = nil
			} else {
				r.CreatedBy.CreatedBy = &tfTypes.IDNamePair1{}
				r.CreatedBy.CreatedBy.ID = types.StringPointerValue(resp.CreatedBy.CreatedBy.ID)
				r.CreatedBy.CreatedBy.Name = types.StringPointerValue(resp.CreatedBy.CreatedBy.Name)
			}
			r.CreatedBy.Email = types.StringPointerValue(resp.CreatedBy.Email)
			if resp.CreatedBy.EnforcementSource != nil {
				r.CreatedBy.EnforcementSource = types.Int32Value(int32(*resp.CreatedBy.EnforcementSource))
			} else {
				r.CreatedBy.EnforcementSource = types.Int32Null()
			}
			if resp.CreatedBy.UserRole != nil {
				r.CreatedBy.UserRole = types.Int32Value(int32(*resp.CreatedBy.UserRole))
			} else {
				r.CreatedBy.UserRole = types.Int32Null()
			}
		}
		r.DeletedAt = types.Int64PointerValue(resp.DeletedAt)
		if resp.DeletedBy == nil {
			r.DeletedBy = nil
		} else {
			r.DeletedBy = &tfTypes.IDNamePair1{}
			r.DeletedBy.ID = types.StringPointerValue(resp.DeletedBy.ID)
			r.DeletedBy.Name = types.StringPointerValue(resp.DeletedBy.Name)
		}
		r.Description = types.StringPointerValue(resp.Description)
		if resp.Direction != nil {
			r.Direction = types.Int32Value(int32(*resp.Direction))
		} else {
			r.Direction = types.Int32Null()
		}
		r.ExcludedEntityInfos = []tfTypes.IDNamePair1{}
		if len(r.ExcludedEntityInfos) > len(resp.ExcludedEntityInfos) {
			r.ExcludedEntityInfos = r.ExcludedEntityInfos[:len(resp.ExcludedEntityInfos)]
		}
		for excludedEntityInfosCount, excludedEntityInfosItem := range resp.ExcludedEntityInfos {
			var excludedEntityInfos tfTypes.IDNamePair1
			excludedEntityInfos.ID = types.StringPointerValue(excludedEntityInfosItem.ID)
			excludedEntityInfos.Name = types.StringPointerValue(excludedEntityInfosItem.Name)
			if excludedEntityInfosCount+1 > len(r.ExcludedEntityInfos) {
				r.ExcludedEntityInfos = append(r.ExcludedEntityInfos, excludedEntityInfos)
			} else {
				r.ExcludedEntityInfos[excludedEntityInfosCount].ID = excludedEntityInfos.ID
				r.ExcludedEntityInfos[excludedEntityInfosCount].Name = excludedEntityInfos.Name
			}
		}
		r.ExcludedLocalIdsList = make([]types.String, 0, len(resp.ExcludedLocalIdsList))
		for _, v := range resp.ExcludedLocalIdsList {
			r.ExcludedLocalIdsList = append(r.ExcludedLocalIdsList, types.StringValue(v))
		}
		r.ExpiresAt = types.Int64PointerValue(resp.ExpiresAt)
		r.ID = types.StringPointerValue(resp.ID)
		if resp.IPSecOpt != nil {
			r.IPSecOpt = types.Int32Value(int32(*resp.IPSecOpt))
		} else {
			r.IPSecOpt = types.Int32Null()
		}
		r.LocalEntityID = types.StringPointerValue(resp.LocalEntityID)
		r.LocalEntityInfos = []tfTypes.LocalEntityInfo{}
		if len(r.LocalEntityInfos) > len(resp.LocalEntityInfos) {
			r.LocalEntityInfos = r.LocalEntityInfos[:len(resp.LocalEntityInfos)]
		}
		for localEntityInfosCount, localEntityInfosItem := range resp.LocalEntityInfos {
			var localEntityInfos tfTypes.LocalEntityInfo
			if localEntityInfosItem.Asset != nil {
				localEntityInfos.Asset = &tfTypes.Asset{}
				if localEntityInfosItem.Asset.AssetStatus != nil {
					localEntityInfos.Asset.AssetStatus = types.Int64Value(int64(*localEntityInfosItem.Asset.AssetStatus))
				} else {
					localEntityInfos.Asset.AssetStatus = types.Int64Null()
				}
				if localEntityInfosItem.Asset.AssetType != nil {
					localEntityInfos.Asset.AssetType = types.Int32Value(int32(*localEntityInfosItem.Asset.AssetType))
				} else {
					localEntityInfos.Asset.AssetType = types.Int32Null()
				}
				if localEntityInfosItem.Asset.AssignedDeployment == nil {
					localEntityInfos.Asset.AssignedDeployment = nil
				} else {
					localEntityInfos.Asset.AssignedDeployment = &tfTypes.IDNamePair1{}
					localEntityInfos.Asset.AssignedDeployment.ID = types.StringPointerValue(localEntityInfosItem.Asset.AssignedDeployment.ID)
					localEntityInfos.Asset.AssignedDeployment.Name = types.StringPointerValue(localEntityInfosItem.Asset.AssignedDeployment.Name)
				}
				localEntityInfos.Asset.AssignedDeploymentID = types.StringPointerValue(localEntityInfosItem.Asset.AssignedDeploymentID)
				localEntityInfos.Asset.BreakGlassActivated = types.BoolPointerValue(localEntityInfosItem.Asset.BreakGlassActivated)
				localEntityInfos.Asset.CloudConnectorVersion = types.StringPointerValue(localEntityInfosItem.Asset.CloudConnectorVersion)
				localEntityInfos.Asset.Domain = types.StringPointerValue(localEntityInfosItem.Asset.Domain)
				if localEntityInfosItem.Asset.EnvironmentGroup == nil {
					localEntityInfos.Asset.EnvironmentGroup = nil
				} else {
					localEntityInfos.Asset.EnvironmentGroup = &tfTypes.IDNamePair1{}
					localEntityInfos.Asset.EnvironmentGroup.ID = types.StringPointerValue(localEntityInfosItem.Asset.EnvironmentGroup.ID)
					localEntityInfos.Asset.EnvironmentGroup.Name = types.StringPointerValue(localEntityInfosItem.Asset.EnvironmentGroup.Name)
				}
				localEntityInfos.Asset.ExternalDeviceID = types.StringPointerValue(localEntityInfosItem.Asset.ExternalDeviceID)
				localEntityInfos.Asset.Fqdn = types.StringPointerValue(localEntityInfosItem.Asset.Fqdn)
				localEntityInfos.Asset.HasDNS = types.BoolPointerValue(localEntityInfosItem.Asset.HasDNS)
				if localEntityInfosItem.Asset.HealthState == nil {
					localEntityInfos.Asset.HealthState = nil
				} else {
					localEntityInfos.Asset.HealthState = &tfTypes.HealthState{}
					localEntityInfos.Asset.HealthState.HealthIssuesList = []tfTypes.HealthIssue{}
					for healthIssuesListCount, healthIssuesListItem := range localEntityInfosItem.Asset.HealthState.HealthIssuesList {
						var healthIssuesList tfTypes.HealthIssue
						healthIssuesList.Details = types.StringPointerValue(healthIssuesListItem.Details)
						if healthIssuesListItem.IssueCode != nil {
							healthIssuesList.IssueCode = types.Int32Value(int32(*healthIssuesListItem.IssueCode))
						} else {
							healthIssuesList.IssueCode = types.Int32Null()
						}
						if healthIssuesListCount+1 > len(localEntityInfos.Asset.HealthState.HealthIssuesList) {
							localEntityInfos.Asset.HealthState.HealthIssuesList = append(localEntityInfos.Asset.HealthState.HealthIssuesList, healthIssuesList)
						} else {
							localEntityInfos.Asset.HealthState.HealthIssuesList[healthIssuesListCount].Details = healthIssuesList.Details
							localEntityInfos.Asset.HealthState.HealthIssuesList[healthIssuesListCount].IssueCode = healthIssuesList.IssueCode
						}
					}
					if localEntityInfosItem.Asset.HealthState.HealthStatus != nil {
						localEntityInfos.Asset.HealthState.HealthStatus = types.Int32Value(int32(*localEntityInfosItem.Asset.HealthState.HealthStatus))
					} else {
						localEntityInfos.Asset.HealthState.HealthStatus = types.Int32Null()
					}
				}
				localEntityInfos.Asset.ID = types.StringPointerValue(localEntityInfosItem.Asset.ID)
				localEntityInfos.Asset.IdentityProtectAt = types.Int64PointerValue(localEntityInfosItem.Asset.IdentityProtectAt)
				localEntityInfos.Asset.IdentityProtectedAt = types.Int64PointerValue(localEntityInfosItem.Asset.IdentityProtectedAt)
				localEntityInfos.Asset.IdentityProtectionState = types.Int64PointerValue(localEntityInfosItem.Asset.IdentityProtectionState)
				if localEntityInfosItem.Asset.InactiveReason != nil {
					localEntityInfos.Asset.InactiveReason = types.Int32Value(int32(*localEntityInfosItem.Asset.InactiveReason))
				} else {
					localEntityInfos.Asset.InactiveReason = types.Int32Null()
				}
				localEntityInfos.Asset.InactiveSince = types.Int64PointerValue(localEntityInfosItem.Asset.InactiveSince)
				localEntityInfos.Asset.IPV4Addresses = make([]types.String, 0, len(localEntityInfosItem.Asset.IPV4Addresses))
				for _, v := range localEntityInfosItem.Asset.IPV4Addresses {
					localEntityInfos.Asset.IPV4Addresses = append(localEntityInfos.Asset.IPV4Addresses, types.StringValue(v))
				}
				localEntityInfos.Asset.IPV6Addresses = make([]types.String, 0, len(localEntityInfosItem.Asset.IPV6Addresses))
				for _, v := range localEntityInfosItem.Asset.IPV6Addresses {
					localEntityInfos.Asset.IPV6Addresses = append(localEntityInfos.Asset.IPV6Addresses, types.StringValue(v))
				}
				localEntityInfos.Asset.IsQuarantined = types.BoolPointerValue(localEntityInfosItem.Asset.IsQuarantined)
				localEntityInfos.Asset.LastLogon = types.Int64PointerValue(localEntityInfosItem.Asset.LastLogon)
				localEntityInfos.Asset.Manufacturer = types.StringPointerValue(localEntityInfosItem.Asset.Manufacturer)
				localEntityInfos.Asset.Name = types.StringPointerValue(localEntityInfosItem.Asset.Name)
				localEntityInfos.Asset.OperatingSystem = types.StringPointerValue(localEntityInfosItem.Asset.OperatingSystem)
				localEntityInfos.Asset.OsType = types.Int64PointerValue(localEntityInfosItem.Asset.OsType)
				if localEntityInfosItem.Asset.OtLocattion == nil {
					localEntityInfos.Asset.OtLocattion = nil
				} else {
					localEntityInfos.Asset.OtLocattion = &tfTypes.OtLocation{}
					localEntityInfos.Asset.OtLocattion.InterfaceName = types.StringPointerValue(localEntityInfosItem.Asset.OtLocattion.InterfaceName)
					localEntityInfos.Asset.OtLocattion.Name = types.StringPointerValue(localEntityInfosItem.Asset.OtLocattion.Name)
					localEntityInfos.Asset.OtLocattion.SwitchID = types.StringPointerValue(localEntityInfosItem.Asset.OtLocattion.SwitchID)
				}
				localEntityInfos.Asset.OutboundRestriction = types.Int64PointerValue(localEntityInfosItem.Asset.OutboundRestriction)
				localEntityInfos.Asset.PasswordUpdateTime = types.Int64PointerValue(localEntityInfosItem.Asset.PasswordUpdateTime)
				if localEntityInfosItem.Asset.PreferredDeployment == nil {
					localEntityInfos.Asset.PreferredDeployment = nil
				} else {
					localEntityInfos.Asset.PreferredDeployment = &tfTypes.IDNamePair1{}
					localEntityInfos.Asset.PreferredDeployment.ID = types.StringPointerValue(localEntityInfosItem.Asset.PreferredDeployment.ID)
					localEntityInfos.Asset.PreferredDeployment.Name = types.StringPointerValue(localEntityInfosItem.Asset.PreferredDeployment.Name)
				}
				localEntityInfos.Asset.PreferredDeploymentID = types.StringPointerValue(localEntityInfosItem.Asset.PreferredDeploymentID)
				localEntityInfos.Asset.PrincipalName = types.StringPointerValue(localEntityInfosItem.Asset.PrincipalName)
				localEntityInfos.Asset.ProtectAt = types.Int64PointerValue(localEntityInfosItem.Asset.ProtectAt)
				localEntityInfos.Asset.ProtectedAt = types.Int64PointerValue(localEntityInfosItem.Asset.ProtectedAt)
				if localEntityInfosItem.Asset.ProtectionState != nil {
					localEntityInfos.Asset.ProtectionState = types.Int32Value(int32(*localEntityInfosItem.Asset.ProtectionState))
				} else {
					localEntityInfos.Asset.ProtectionState = types.Int32Null()
				}
				localEntityInfos.Asset.PurdueLevel = types.Int64PointerValue(localEntityInfosItem.Asset.PurdueLevel)
				localEntityInfos.Asset.RPCMonitored = types.BoolPointerValue(localEntityInfosItem.Asset.RPCMonitored)
				localEntityInfos.Asset.RPCProtectAt = types.Int64PointerValue(localEntityInfosItem.Asset.RPCProtectAt)
				localEntityInfos.Asset.RPCProtectedAt = types.Int64PointerValue(localEntityInfosItem.Asset.RPCProtectedAt)
				localEntityInfos.Asset.RPCProtectionState = types.Int64PointerValue(localEntityInfosItem.Asset.RPCProtectionState)
				if localEntityInfosItem.Asset.Source != nil {
					localEntityInfos.Asset.Source = types.Int32Value(int32(*localEntityInfosItem.Asset.Source))
				} else {
					localEntityInfos.Asset.Source = types.Int32Null()
				}
				if localEntityInfosItem.Asset.State == nil {
					localEntityInfos.Asset.State = nil
				} else {
					localEntityInfos.Asset.State = &tfTypes.AssetState{}
					localEntityInfos.Asset.State.AssetID = types.StringPointerValue(localEntityInfosItem.Asset.State.AssetID)
					localEntityInfos.Asset.State.IdentityProtectionState = types.Int64PointerValue(localEntityInfosItem.Asset.State.IdentityProtectionState)
					localEntityInfos.Asset.State.IsAssetConnected = types.BoolPointerValue(localEntityInfosItem.Asset.State.IsAssetConnected)
					localEntityInfos.Asset.State.LastConnectedAt = types.Int64PointerValue(localEntityInfosItem.Asset.State.LastConnectedAt)
					localEntityInfos.Asset.State.ProtectedAt = types.Int64PointerValue(localEntityInfosItem.Asset.State.ProtectedAt)
					localEntityInfos.Asset.State.ProtectionState = types.Int64PointerValue(localEntityInfosItem.Asset.State.ProtectionState)
					localEntityInfos.Asset.State.RPCProtectionState = types.Int64PointerValue(localEntityInfosItem.Asset.State.RPCProtectionState)
				}
				localEntityInfos.Asset.SwitchLocationOverridden = types.BoolPointerValue(localEntityInfosItem.Asset.SwitchLocationOverridden)
			}
			if localEntityInfosItem.GroupBasicInfo != nil {
				localEntityInfos.GroupBasicInfo = &tfTypes.GroupBasicInfo{}
				localEntityInfos.GroupBasicInfo.Domain = types.StringPointerValue(localEntityInfosItem.GroupBasicInfo.Domain)
				localEntityInfos.GroupBasicInfo.GUID = types.StringPointerValue(localEntityInfosItem.GroupBasicInfo.GUID)
				localEntityInfos.GroupBasicInfo.HasIdentityProtectionPolicy = types.BoolPointerValue(localEntityInfosItem.GroupBasicInfo.HasIdentityProtectionPolicy)
				localEntityInfos.GroupBasicInfo.HasNetworkProtectionPolicy = types.BoolPointerValue(localEntityInfosItem.GroupBasicInfo.HasNetworkProtectionPolicy)
				localEntityInfos.GroupBasicInfo.ID = types.StringPointerValue(localEntityInfosItem.GroupBasicInfo.ID)
				localEntityInfos.GroupBasicInfo.Name = types.StringPointerValue(localEntityInfosItem.GroupBasicInfo.Name)
				localEntityInfos.GroupBasicInfo.Sid = types.StringPointerValue(localEntityInfosItem.GroupBasicInfo.Sid)
			}
			if localEntityInfosCount+1 > len(r.LocalEntityInfos) {
				r.LocalEntityInfos = append(r.LocalEntityInfos, localEntityInfos)
			} else {
				r.LocalEntityInfos[localEntityInfosCount].Asset = localEntityInfos.Asset
				r.LocalEntityInfos[localEntityInfosCount].GroupBasicInfo = localEntityInfos.GroupBasicInfo
			}
		}
		r.LocalProcessesList = make([]types.String, 0, len(resp.LocalProcessesList))
		for _, v := range resp.LocalProcessesList {
			r.LocalProcessesList = append(r.LocalProcessesList, types.StringValue(v))
		}
		r.MultipleLocalEntityIdsList = make([]types.String, 0, len(resp.MultipleLocalEntityIdsList))
		for _, v := range resp.MultipleLocalEntityIdsList {
			r.MultipleLocalEntityIdsList = append(r.MultipleLocalEntityIdsList, types.StringValue(v))
		}
		r.Name = types.StringPointerValue(resp.Name)
		r.ParentID = types.StringPointerValue(resp.ParentID)
		r.ParentSwitchRuleID = types.StringPointerValue(resp.ParentSwitchRuleID)
		r.ParentSwitchRuleType = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.ParentSwitchRuleType))
		r.ParentType = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.ParentType))
		r.PortsList = []tfTypes.PortsList{}
		if len(r.PortsList) > len(resp.PortsList) {
			r.PortsList = r.PortsList[:len(resp.PortsList)]
		}
		for portsListCount, portsListItem := range resp.PortsList {
			var portsList tfTypes.PortsList
			portsList.Ports = types.StringPointerValue(portsListItem.Ports)
			if portsListItem.ProtocolType != nil {
				portsList.ProtocolType = types.Int32Value(int32(*portsListItem.ProtocolType))
			} else {
				portsList.ProtocolType = types.Int32Null()
			}
			if portsListCount+1 > len(r.PortsList) {
				r.PortsList = append(r.PortsList, portsList)
			} else {
				r.PortsList[portsListCount].Ports = portsList.Ports
				r.PortsList[portsListCount].ProtocolType = portsList.ProtocolType
			}
		}
		r.RemoteEntityIdsList = make([]types.String, 0, len(resp.RemoteEntityIdsList))
		for _, v := range resp.RemoteEntityIdsList {
			r.RemoteEntityIdsList = append(r.RemoteEntityIdsList, types.StringValue(v))
		}
		r.RemoteEntityInfos = []tfTypes.IDNamePair1{}
		if len(r.RemoteEntityInfos) > len(resp.RemoteEntityInfos) {
			r.RemoteEntityInfos = r.RemoteEntityInfos[:len(resp.RemoteEntityInfos)]
		}
		for remoteEntityInfosCount, remoteEntityInfosItem := range resp.RemoteEntityInfos {
			var remoteEntityInfos tfTypes.IDNamePair1
			remoteEntityInfos.ID = types.StringPointerValue(remoteEntityInfosItem.ID)
			remoteEntityInfos.Name = types.StringPointerValue(remoteEntityInfosItem.Name)
			if remoteEntityInfosCount+1 > len(r.RemoteEntityInfos) {
				r.RemoteEntityInfos = append(r.RemoteEntityInfos, remoteEntityInfos)
			} else {
				r.RemoteEntityInfos[remoteEntityInfosCount].ID = remoteEntityInfos.ID
				r.RemoteEntityInfos[remoteEntityInfosCount].Name = remoteEntityInfos.Name
			}
		}
		if resp.Ruleclass != nil {
			r.Ruleclass = types.Int32Value(int32(*resp.Ruleclass))
		} else {
			r.Ruleclass = types.Int32Null()
		}
		if resp.RuleReview == nil {
			r.RuleReview = nil
		} else {
			r.RuleReview = &tfTypes.RuleReviewReason{}
			r.RuleReview.Details = types.StringPointerValue(resp.RuleReview.Details)
			r.RuleReview.Reason = types.Int64Value(resp.RuleReview.Reason)
		}
		r.ServicesList = make([]types.String, 0, len(resp.ServicesList))
		for _, v := range resp.ServicesList {
			r.ServicesList = append(r.ServicesList, types.StringValue(v))
		}
		r.SrcUsersList = []tfTypes.SrcUsersList{}
		if len(r.SrcUsersList) > len(resp.SrcUsersList) {
			r.SrcUsersList = r.SrcUsersList[:len(resp.SrcUsersList)]
		}
		for srcUsersListCount, srcUsersListItem := range resp.SrcUsersList {
			var srcUsersList tfTypes.SrcUsersList
			srcUsersList.ID = types.StringPointerValue(srcUsersListItem.ID)
			srcUsersList.Sid = types.StringPointerValue(srcUsersListItem.Sid)
			if srcUsersListCount+1 > len(r.SrcUsersList) {
				r.SrcUsersList = append(r.SrcUsersList, srcUsersList)
			} else {
				r.SrcUsersList[srcUsersListCount].ID = srcUsersList.ID
				r.SrcUsersList[srcUsersListCount].Sid = srcUsersList.Sid
			}
		}
		if resp.State != nil {
			r.State = types.Int32Value(int32(*resp.State))
		} else {
			r.State = types.Int32Null()
		}
		r.UpdatedAt = types.Int64PointerValue(resp.UpdatedAt)
		if resp.UpdatedBy == nil {
			r.UpdatedBy = nil
		} else {
			r.UpdatedBy = &tfTypes.IDNamePair1{}
			r.UpdatedBy.ID = types.StringPointerValue(resp.UpdatedBy.ID)
			r.UpdatedBy.Name = types.StringPointerValue(resp.UpdatedBy.Name)
		}
	}

	return diags
}
