// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk"
	"github.com/zeronetworks/terraform-provider-zeronetworks/internal/sdk/models/shared"
	"net/http"
)

var _ provider.Provider = (*ZeronetworksProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*ZeronetworksProvider)(nil)

type ZeronetworksProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// ZeronetworksProviderModel describes the provider data model.
type ZeronetworksProviderModel struct {
	APIKey      types.String `tfsdk:"api_key"`
	CustomerURL types.String `tfsdk:"customer_url"`
	ServerURL   types.String `tfsdk:"server_url"`
}

func (p *ZeronetworksProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "zeronetworks"
	resp.Version = p.version
}

func (p *ZeronetworksProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				MarkdownDescription: `API Key.`,
				Required:            true,
				Sensitive:           true,
			},
			"customer_url": schema.StringAttribute{
				MarkdownDescription: `this value is per customer / partner (defaults to portal)`,
				Optional:            true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://portal.zeronetworks.com/v1/api)`,
				Optional:    true,
			},
		},
		MarkdownDescription: `Zero Networks: APIs for Zero Networks`,
	}
}

func (p *ZeronetworksProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data ZeronetworksProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://portal.zeronetworks.com/v1/api"
	}

	serverUrlParams := make(map[string]string)

	if data.CustomerURL.ValueString() != "" {
		serverUrlParams["CustomerURL"] = data.CustomerURL.ValueString()
	}

	if _, ok := serverUrlParams["CustomerURL"]; !ok {
		serverUrlParams["CustomerURL"] = "portal"
	}

	security := shared.Security{}

	if !data.APIKey.IsUnknown() {
		security.APIKey = data.APIKey.ValueString()
	}

	if security.APIKey == "" {
		resp.Diagnostics.AddError(
			"Missing Provider Security Configuration",
			"Provider configuration api_key attribute must be configured.",
		)
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithTemplatedServerURL(serverUrl, serverUrlParams),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ResourceData = client
}

func (p *ZeronetworksProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewCustomGroupResource,
		NewCustomGroupMembersResource,
		NewInboundMFAPolicyResource,
		NewInboundRuleResource,
		NewOutboundMFAPolicyResource,
		NewOutboundRuleResource,
		NewRPCRuleResource,
	}
}

func (p *ZeronetworksProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAssetIDDataSource,
		NewCustomGroupDataSource,
		NewCustomGroupMembersDataSource,
		NewInboundMFAPolicyDataSource,
		NewInboundRuleDataSource,
		NewOutboundMFAPolicyDataSource,
		NewOutboundRuleDataSource,
		NewRPCRuleDataSource,
	}
}

func (p *ZeronetworksProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &ZeronetworksProvider{
			version: version,
		}
	}
}
