// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Asset struct {
	AssetStatus              types.Int64    `tfsdk:"asset_status"`
	AssetType                types.Int32    `tfsdk:"asset_type"`
	AssignedDeploymentID     types.String   `tfsdk:"assigned_deployment_id"`
	BreakGlassActivated      types.Bool     `tfsdk:"break_glass_activated"`
	Domain                   types.String   `tfsdk:"domain"`
	ExternalDeviceID         types.String   `tfsdk:"external_device_id"`
	Fqdn                     types.String   `tfsdk:"fqdn"`
	HasDNS                   types.Bool     `tfsdk:"has_dns"`
	HealthState              *HealthState   `tfsdk:"health_state"`
	ID                       types.String   `tfsdk:"id"`
	IdentityProtectAt        types.Int64    `tfsdk:"identity_protect_at"`
	IdentityProtectedAt      types.Int64    `tfsdk:"identity_protected_at"`
	IdentityProtectionState  types.Int64    `tfsdk:"identity_protection_state"`
	InactiveReason           types.Int32    `tfsdk:"inactive_reason"`
	InactiveSince            types.Int64    `tfsdk:"inactive_since"`
	IPV4Addresses            []types.String `tfsdk:"ip_v4_addresses"`
	IPV6Addresses            []types.String `tfsdk:"ip_v6_addresses"`
	IsQuarantined            types.Bool     `tfsdk:"is_quarantined"`
	LastLogon                types.Int64    `tfsdk:"last_logon"`
	Manufacturer             types.String   `tfsdk:"manufacturer"`
	Name                     types.String   `tfsdk:"name"`
	OperatingSystem          types.String   `tfsdk:"operating_system"`
	OsType                   types.Int64    `tfsdk:"os_type"`
	OtLocattion              *OtLocation    `tfsdk:"ot_locattion"`
	OutboundRestriction      types.Int64    `tfsdk:"outbound_restriction"`
	PasswordUpdateTime       types.Int64    `tfsdk:"password_update_time"`
	PreferredDeploymentID    types.String   `tfsdk:"preferred_deployment_id"`
	PrincipalName            types.String   `tfsdk:"principal_name"`
	ProtectAt                types.Int64    `tfsdk:"protect_at"`
	ProtectedAt              types.Int64    `tfsdk:"protected_at"`
	ProtectionState          types.Int32    `tfsdk:"protection_state"`
	PurdueLevel              types.Int64    `tfsdk:"purdue_level"`
	RPCMonitored             types.Bool     `tfsdk:"rpc_monitored"`
	RPCProtectAt             types.Int64    `tfsdk:"rpc_protect_at"`
	RPCProtectedAt           types.Int64    `tfsdk:"rpc_protected_at"`
	RPCProtectionState       types.Int64    `tfsdk:"rpc_protection_state"`
	Source                   types.Int32    `tfsdk:"source"`
	SwitchLocationOverridden types.Bool     `tfsdk:"switch_location_overridden"`
}
