// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Conditions struct {
	AssetTypes     []types.Int64  `tfsdk:"asset_types"`
	NamePatterns   []types.String `tfsdk:"name_patterns"`
	OsNamePatterns []types.String `tfsdk:"os_name_patterns"`
	OsTypes        []types.Int64  `tfsdk:"os_types"`
}
