// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Group struct {
	AddedAt             types.Int64   `tfsdk:"added_at"`
	AddedBy             *GroupAddedBy `tfsdk:"added_by"`
	CreatedAt           types.Int64   `tfsdk:"created_at"`
	Description         types.String  `tfsdk:"description"`
	DirectMembersCount  types.Int64   `tfsdk:"direct_members_count"`
	Domain              types.String  `tfsdk:"domain"`
	ExternalID          types.String  `tfsdk:"external_id"`
	GUID                types.String  `tfsdk:"guid"`
	HasProtectionPolicy types.Bool    `tfsdk:"has_protection_policy"`
	ID                  types.String  `tfsdk:"id"`
	Name                types.String  `tfsdk:"name"`
	PrincipalName       types.String  `tfsdk:"principal_name"`
	Role                types.Int32   `tfsdk:"role"`
	Sid                 types.String  `tfsdk:"sid"`
	UpdatedAt           types.Int64   `tfsdk:"updated_at"`
}
