// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type HealthIssue struct {
	Details   types.String `tfsdk:"details"`
	IssueCode types.Int32  `tfsdk:"issue_code"`
}
