// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type LocalEntityInfo struct {
	Asset          *Asset          `queryParam:"inline" tfsdk:"asset" tfPlanOnly:"true"`
	GroupBasicInfo *GroupBasicInfo `queryParam:"inline" tfsdk:"group_basic_info" tfPlanOnly:"true"`
}
