// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type LocalEntityInfo struct {
	Asset *Asset `queryParam:"inline" tfsdk:"asset" tfPlanOnly:"true"`
	Group *Group `queryParam:"inline" tfsdk:"group" tfPlanOnly:"true"`
}
